/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-25 14:47:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layouts;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class other_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/SACHINTHA/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244559614L));
    _jspx_dependants.put("jar:file:/C:/Users/SACHINTHA/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>Luminary Clothing</title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"keywords\" content=\"Marketplace ecommerce responsive HTML5 Template\" />\r\n");
      out.write("    <meta name=\"description\" content=\"Wolmart is powerful marketplace &amp; ecommerce responsive Html5 Template.\">\r\n");
      out.write("    <meta name=\"author\" content=\"D-THEMES\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"assets/images/icons/luminary_logo.png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- WebFont.js -->\r\n");
      out.write("    <script>\r\n");
      out.write("        WebFontConfig = {\r\n");
      out.write("            google: { families: ['Poppins:400,500,600,700'] }\r\n");
      out.write("        };\r\n");
      out.write("        (function (d) {\r\n");
      out.write("            var wf = d.createElement('script'), s = d.scripts[0];\r\n");
      out.write("            wf.src = 'assets/js/webfont.js';\r\n");
      out.write("            wf.async = true;\r\n");
      out.write("            s.parentNode.insertBefore(wf, s);\r\n");
      out.write("        })(document);\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"preload\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/fontawesome-free/webfonts/fa-regular-400.woff2\" as=\"font\" type=\"font/woff2\"\r\n");
      out.write("          crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"preload\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/fontawesome-free/webfonts/fa-solid-900.woff2\" as=\"font\" type=\"font/woff2\"\r\n");
      out.write("          crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"preload\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/fontawesome-free/webfonts/fa-brands-400.woff2\" as=\"font\" type=\"font/woff2\"\r\n");
      out.write("          crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"preload\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/fonts/wolmart.woff?png09e\" as=\"font\" type=\"font/woff\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Vendor CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/fontawesome-free/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/animate/animate.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Plugins CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/swiper/swiper-bundle.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/nouislider/nouislider.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/magnific-popup/magnific-popup.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Default CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/style.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"page-wrapper\">\r\n");
      out.write("    <h1 class=\"d-none\">Wolmart - Responsive Marketplace HTML Template</h1>\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fblock_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../frontend/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End of Page Wrapper -->\r\n");
      out.write("\r\n");
      out.write("<!-- Start of Sticky Footer -->\r\n");
      out.write("<div class=\"sticky-footer sticky-content fix-bottom\">\r\n");
      out.write("    <a href=\"demo1.html\" class=\"sticky-link active\">\r\n");
      out.write("        <i class=\"w-icon-home\"></i>\r\n");
      out.write("        <p>Home</p>\r\n");
      out.write("    </a>\r\n");
      out.write("    <a href=\"shop-banner-sidebar.html\" class=\"sticky-link\">\r\n");
      out.write("        <i class=\"w-icon-category\"></i>\r\n");
      out.write("        <p>Shop</p>\r\n");
      out.write("    </a>\r\n");
      out.write("    <a href=\"my-account.html\" class=\"sticky-link\">\r\n");
      out.write("        <i class=\"w-icon-account\"></i>\r\n");
      out.write("        <p>Account</p>\r\n");
      out.write("    </a>\r\n");
      out.write("    <div class=\"cart-dropdown dir-up\">\r\n");
      out.write("        <a href=\"cart.html\" class=\"sticky-link\">\r\n");
      out.write("            <i class=\"w-icon-cart\"></i>\r\n");
      out.write("            <p>Cart</p>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown-box\">\r\n");
      out.write("            <div class=\"products\">\r\n");
      out.write("                <div class=\"product product-cart\">\r\n");
      out.write("                    <div class=\"product-detail\">\r\n");
      out.write("                        <h3 class=\"product-name\">\r\n");
      out.write("                            <a href=\"product-default.html\">Beige knitted elas<br>tic\r\n");
      out.write("                                runner shoes</a>\r\n");
      out.write("                        </h3>\r\n");
      out.write("                        <div class=\"price-box\">\r\n");
      out.write("                            <span class=\"product-quantity\">1</span>\r\n");
      out.write("                            <span class=\"product-price\">$25.68</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <figure class=\"product-media\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"assets/images/cart/product-1.jpg\" alt=\"product\" height=\"84\" width=\"94\" />\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </figure>\r\n");
      out.write("                    <button class=\"btn btn-link btn-close\" aria-label=\"button\">\r\n");
      out.write("                        <i class=\"fas fa-times\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"product product-cart\">\r\n");
      out.write("                    <div class=\"product-detail\">\r\n");
      out.write("                        <h3 class=\"product-name\">\r\n");
      out.write("                            <a href=\"product.html\">Blue utility pina<br>fore\r\n");
      out.write("                                denim dress</a>\r\n");
      out.write("                        </h3>\r\n");
      out.write("                        <div class=\"price-box\">\r\n");
      out.write("                            <span class=\"product-quantity\">1</span>\r\n");
      out.write("                            <span class=\"product-price\">$32.99</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <figure class=\"product-media\">\r\n");
      out.write("                        <a href=\"#\">\r\n");
      out.write("                            <img src=\"assets/images/cart/product-2.jpg\" alt=\"product\" width=\"84\" height=\"94\" />\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </figure>\r\n");
      out.write("                    <button class=\"btn btn-link btn-close\" aria-label=\"button\">\r\n");
      out.write("                        <i class=\"fas fa-times\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cart-total\">\r\n");
      out.write("                <label>Subtotal:</label>\r\n");
      out.write("                <span class=\"price\">$58.67</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cart-action\">\r\n");
      out.write("                <a href=\"cart.html\" class=\"btn btn-dark btn-outline btn-rounded\">View Cart</a>\r\n");
      out.write("                <a href=\"checkout.html\" class=\"btn btn-primary  btn-rounded\">Checkout</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of Dropdown Box -->\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"header-search hs-toggle dir-up\">\r\n");
      out.write("        <a href=\"#\" class=\"search-toggle sticky-link\">\r\n");
      out.write("            <i class=\"w-icon-search\"></i>\r\n");
      out.write("            <p>Search</p>\r\n");
      out.write("        </a>\r\n");
      out.write("        <form action=\"#\" class=\"input-wrapper\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"search\" autocomplete=\"off\" placeholder=\"Search\"\r\n");
      out.write("                   required />\r\n");
      out.write("            <button class=\"btn btn-search\" type=\"submit\">\r\n");
      out.write("                <i class=\"w-icon-search\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End of Sticky Footer -->\r\n");
      out.write("\r\n");
      out.write("<!-- Start of Scroll Top -->\r\n");
      out.write("<a id=\"scroll-top\" class=\"scroll-top\" href=\"#top\" title=\"Top\" role=\"button\"> <i class=\"w-icon-angle-up\"></i> <svg version=\"1.1\" xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 70 70\"> <circle id=\"progress-indicator\" fill=\"transparent\" stroke=\"#000000\" stroke-miterlimit=\"10\" cx=\"35\" cy=\"35\" r=\"34\" style=\"stroke-dasharray: 16.4198, 400;\"></circle> </svg> </a>\r\n");
      out.write("<!-- End of Scroll Top -->\r\n");
      out.write("\r\n");
      out.write("<!-- Start of Mobile Menu -->\r\n");
      out.write("<div class=\"mobile-menu-wrapper\">\r\n");
      out.write("    <div class=\"mobile-menu-overlay\"></div>\r\n");
      out.write("    <!-- End of .mobile-menu-overlay -->\r\n");
      out.write("\r\n");
      out.write("    <a href=\"#\" class=\"mobile-menu-close\"><i class=\"close-icon\"></i></a>\r\n");
      out.write("    <!-- End of .mobile-menu-close -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"mobile-menu-container scrollable\">\r\n");
      out.write("        <form action=\"#\" method=\"get\" class=\"input-wrapper\">\r\n");
      out.write("            <input type=\"text\" class=\"form-control\" name=\"search\" autocomplete=\"off\" placeholder=\"Search\"\r\n");
      out.write("                   required />\r\n");
      out.write("            <button class=\"btn btn-search\" type=\"submit\">\r\n");
      out.write("                <i class=\"w-icon-search\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("        </form>\r\n");
      out.write("        <!-- End of Search Form -->\r\n");
      out.write("        <div class=\"tab\">\r\n");
      out.write("            <ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"#main-menu\" class=\"nav-link active\">Main Menu</a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a href=\"#categories\" class=\"nav-link\">Categories</a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tab-content\">\r\n");
      out.write("            <div class=\"tab-pane active\" id=\"main-menu\">\r\n");
      out.write("                <ul class=\"mobile-menu\">\r\n");
      out.write("                    <li><a href=\"demo1.html\">Home</a></li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"shop-banner-sidebar.html\">Shop</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Shop Pages</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-banner-sidebar.html\">Banner With Sidebar</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-boxed-banner.html\">Boxed Banner</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Full Width Banner</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-horizontal-filter.html\">Horizontal Filter<span\r\n");
      out.write("                                            class=\"tip tip-hot\">Hot</span></a></li>\r\n");
      out.write("                                    <li><a href=\"shop-off-canvas.html\">Off Canvas Sidebar<span\r\n");
      out.write("                                            class=\"tip tip-new\">New</span></a></li>\r\n");
      out.write("                                    <li><a href=\"shop-infinite-scroll.html\">Infinite Ajax Scroll</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-right-sidebar.html\">Right Sidebar</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-both-sidebar.html\">Both Sidebar</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Shop Layouts</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-grid-3cols.html\">3 Columns Mode</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-grid-4cols.html\">4 Columns Mode</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-grid-5cols.html\">5 Columns Mode</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-grid-6cols.html\">6 Columns Mode</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-grid-7cols.html\">7 Columns Mode</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-grid-8cols.html\">8 Columns Mode</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-list.html\">List Mode</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-list-sidebar.html\">List Mode With Sidebar</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Product Pages</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"product-variable.html\">Variable Product</a></li>\r\n");
      out.write("                                    <li><a href=\"product-featured.html\">Featured &amp; Sale</a></li>\r\n");
      out.write("                                    <li><a href=\"product-accordion.html\">Data In Accordion</a></li>\r\n");
      out.write("                                    <li><a href=\"product-section.html\">Data In Sections</a></li>\r\n");
      out.write("                                    <li><a href=\"product-swatch.html\">Image Swatch</a></li>\r\n");
      out.write("                                    <li><a href=\"product-extended.html\">Extended Info</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"product-without-sidebar.html\">Without Sidebar</a></li>\r\n");
      out.write("                                    <li><a href=\"product-video.html\">360<sup>o</sup> &amp; Video<span\r\n");
      out.write("                                            class=\"tip tip-new\">New</span></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Product Layouts</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"product-default.html\">Default<span\r\n");
      out.write("                                            class=\"tip tip-hot\">Hot</span></a></li>\r\n");
      out.write("                                    <li><a href=\"product-vertical.html\">Vertical Thumbs</a></li>\r\n");
      out.write("                                    <li><a href=\"product-grid.html\">Grid Images</a></li>\r\n");
      out.write("                                    <li><a href=\"product-masonry.html\">Masonry</a></li>\r\n");
      out.write("                                    <li><a href=\"product-gallery.html\">Gallery</a></li>\r\n");
      out.write("                                    <li><a href=\"product-sticky-info.html\">Sticky Info</a></li>\r\n");
      out.write("                                    <li><a href=\"product-sticky-thumb.html\">Sticky Thumbs</a></li>\r\n");
      out.write("                                    <li><a href=\"product-sticky-both.html\">Sticky Both</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"vendor-dokan-store.html\">Vendor</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Store Listing</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"vendor-dokan-store-list.html\">Store listing 1</a></li>\r\n");
      out.write("                                    <li><a href=\"vendor-wcfm-store-list.html\">Store listing 2</a></li>\r\n");
      out.write("                                    <li><a href=\"vendor-wcmp-store-list.html\">Store listing 3</a></li>\r\n");
      out.write("                                    <li><a href=\"vendor-wc-store-list.html\">Store listing 4</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Vendor Store</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"vendor-dokan-store.html\">Vendor Store 1</a></li>\r\n");
      out.write("                                    <li><a href=\"vendor-wcfm-store-product-grid.html\">Vendor Store 2</a></li>\r\n");
      out.write("                                    <li><a href=\"vendor-wcmp-store-product-grid.html\">Vendor Store 3</a></li>\r\n");
      out.write("                                    <li><a href=\"vendor-wc-store-product-grid.html\">Vendor Store 4</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"blog.html\">Blog</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"blog.html\">Classic</a></li>\r\n");
      out.write("                            <li><a href=\"blog-listing.html\">Listing</a></li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"blog-grid.html\">Grid</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"blog-grid-2cols.html\">Grid 2 columns</a></li>\r\n");
      out.write("                                    <li><a href=\"blog-grid-3cols.html\">Grid 3 columns</a></li>\r\n");
      out.write("                                    <li><a href=\"blog-grid-4cols.html\">Grid 4 columns</a></li>\r\n");
      out.write("                                    <li><a href=\"blog-grid-sidebar.html\">Grid sidebar</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Masonry</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"blog-masonry-2cols.html\">Masonry 2 columns</a></li>\r\n");
      out.write("                                    <li><a href=\"blog-masonry-3cols.html\">Masonry 3 columns</a></li>\r\n");
      out.write("                                    <li><a href=\"blog-masonry-4cols.html\">Masonry 4 columns</a></li>\r\n");
      out.write("                                    <li><a href=\"blog-masonry-sidebar.html\">Masonry sidebar</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Mask</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"blog-mask-grid.html\">Blog mask grid</a></li>\r\n");
      out.write("                                    <li><a href=\"blog-mask-masonry.html\">Blog mask masonry</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"post-single.html\">Single Post</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"about-us.html\">Pages</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("\r\n");
      out.write("                            <li><a href=\"about-us.html\">About Us</a></li>\r\n");
      out.write("                            <li><a href=\"become-a-vendor.html\">Become A Vendor</a></li>\r\n");
      out.write("                            <li><a href=\"contact-us.html\">Contact Us</a></li>\r\n");
      out.write("                            <li><a href=\"login.html\">Login</a></li>\r\n");
      out.write("                            <li><a href=\"faq.html\">FAQs</a></li>\r\n");
      out.write("                            <li><a href=\"error-404.html\">Error 404</a></li>\r\n");
      out.write("                            <li><a href=\"coming-soon.html\">Coming Soon</a></li>\r\n");
      out.write("                            <li><a href=\"wishlist.html\">Wishlist</a></li>\r\n");
      out.write("                            <li><a href=\"cart.html\">Cart</a></li>\r\n");
      out.write("                            <li><a href=\"checkout.html\">Checkout</a></li>\r\n");
      out.write("                            <li><a href=\"my-account.html\">My Account</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"elements.html\">Elements</a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"element-products.html\">Products</a></li>\r\n");
      out.write("                            <li><a href=\"element-titles.html\">Titles</a></li>\r\n");
      out.write("                            <li><a href=\"element-typography.html\">Typography</a></li>\r\n");
      out.write("                            <li><a href=\"element-categories.html\">Product Category</a></li>\r\n");
      out.write("                            <li><a href=\"element-buttons.html\">Buttons</a></li>\r\n");
      out.write("                            <li><a href=\"element-accordions.html\">Accordions</a></li>\r\n");
      out.write("                            <li><a href=\"element-alerts.html\">Alert &amp; Notification</a></li>\r\n");
      out.write("                            <li><a href=\"element-tabs.html\">Tabs</a></li>\r\n");
      out.write("                            <li><a href=\"element-testimonials.html\">Testimonials</a></li>\r\n");
      out.write("                            <li><a href=\"element-blog-posts.html\">Blog Posts</a></li>\r\n");
      out.write("                            <li><a href=\"element-instagrams.html\">Instagrams</a></li>\r\n");
      out.write("                            <li><a href=\"element-cta.html\">Call to Action</a></li>\r\n");
      out.write("                            <li><a href=\"element-vendors.html\">Vendors</a></li>\r\n");
      out.write("                            <li><a href=\"element-icon-boxes.html\">Icon Boxes</a></li>\r\n");
      out.write("                            <li><a href=\"element-icons.html\">Icons</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"tab-pane\" id=\"categories\">\r\n");
      out.write("                <ul class=\"mobile-menu\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                            <i class=\"w-icon-tshirt2\"></i>Fashion\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Women</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">New Arrivals</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Best Sellers</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Trending</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Clothing</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Shoes</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Bags</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Accessories</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Jewlery &\r\n");
      out.write("                                        Watches</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Sale</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Men</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">New Arrivals</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Best Sellers</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Trending</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Clothing</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Shoes</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Bags</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Accessories</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Jewlery &\r\n");
      out.write("                                        Watches</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                            <i class=\"w-icon-home\"></i>Home & Garden\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Bedroom</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Beds, Frames &\r\n");
      out.write("                                        Bases</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Dressers</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Nightstands</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Kid's Beds &\r\n");
      out.write("                                        Headboards</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Armoires</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Living Room</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Coffee Tables</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Chairs</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Tables</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Futons & Sofa\r\n");
      out.write("                                        Beds</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Cabinets &\r\n");
      out.write("                                        Chests</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Office</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Office Chairs</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Desks</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Bookcases</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">File Cabinets</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Breakroom\r\n");
      out.write("                                        Tables</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Kitchen & Dining</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Dining Sets</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Kitchen Storage\r\n");
      out.write("                                        Cabinets</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Bashers Racks</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Dining Chairs</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Dining Room\r\n");
      out.write("                                        Tables</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Bar Stools</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                            <i class=\"w-icon-electronics\"></i>Electronics\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Laptops &amp; Computers</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Desktop\r\n");
      out.write("                                        Computers</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Monitors</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Laptops</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Hard Drives &amp;\r\n");
      out.write("                                        Storage</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Computer\r\n");
      out.write("                                        Accessories</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">TV &amp; Video</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">TVs</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Home Audio\r\n");
      out.write("                                        Speakers</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Projectors</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Media Streaming\r\n");
      out.write("                                        Devices</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Digital Cameras</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Digital SLR\r\n");
      out.write("                                        Cameras</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Sports & Action\r\n");
      out.write("                                        Cameras</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Camera Lenses</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Photo Printer</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Digital Memory\r\n");
      out.write("                                        Cards</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Cell Phones</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Carrier Phones</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Unlocked Phones</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Phone & Cellphone\r\n");
      out.write("                                        Cases</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Cellphone\r\n");
      out.write("                                        Chargers</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                            <i class=\"w-icon-furniture\"></i>Furniture\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Furniture</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Sofas & Couches</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Armchairs</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Bed Frames</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Beside Tables</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Dressing Tables</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Lighting</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Light Bulbs</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Lamps</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Celling Lights</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Wall Lights</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Bathroom\r\n");
      out.write("                                        Lighting</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Home Accessories</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Decorative\r\n");
      out.write("                                        Accessories</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Candals &\r\n");
      out.write("                                        Holders</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Home Fragrance</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Mirrors</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Clocks</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"#\">Garden & Outdoors</a>\r\n");
      out.write("                                <ul>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Garden\r\n");
      out.write("                                        Furniture</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Lawn Mowers</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Pressure\r\n");
      out.write("                                        Washers</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">All Garden\r\n");
      out.write("                                        Tools</a></li>\r\n");
      out.write("                                    <li><a href=\"shop-fullwidth-banner.html\">Outdoor Dining</a>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                            <i class=\"w-icon-heartbeat\"></i>Healthy & Beauty\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                            <i class=\"w-icon-gift\"></i>Gift Ideas\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                            <i class=\"w-icon-gamepad\"></i>Toy & Games\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                            <i class=\"w-icon-ice-cream\"></i>Cooking\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                            <i class=\"w-icon-ios\"></i>Smart Phones\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                            <i class=\"w-icon-camera\"></i>Cameras & Photo\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                            <i class=\"w-icon-ruby\"></i>Accessories\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"shop-banner-sidebar.html\"\r\n");
      out.write("                           class=\"font-weight-bold text-primary text-uppercase ls-25\">\r\n");
      out.write("                            View All Categories<i class=\"w-icon-angle-right\"></i>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End of Mobile Menu -->\r\n");
      out.write("\r\n");
      out.write("<!-- Start of Quick View -->\r\n");
      out.write("<div class=\"product product-single product-popup\">\r\n");
      out.write("    <div class=\"row gutter-lg\">\r\n");
      out.write("        <div class=\"col-md-6 mb-4 mb-md-0\">\r\n");
      out.write("            <div class=\"product-gallery product-gallery-sticky\">\r\n");
      out.write("                <div class=\"swiper-container product-single-swiper swiper-theme nav-inner\">\r\n");
      out.write("                    <div class=\"swiper-wrapper row cols-1 gutter-no\">\r\n");
      out.write("                        <div class=\"swiper-slide\">\r\n");
      out.write("                            <figure class=\"product-image\">\r\n");
      out.write("                                <img src=\"assets/images/products/popup/1-440x494.jpg\"\r\n");
      out.write("                                     data-zoom-image=\"assets/images/products/popup/1-800x900.jpg\"\r\n");
      out.write("                                     alt=\"Water Boil Black Utensil\" width=\"800\" height=\"900\">\r\n");
      out.write("                            </figure>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"swiper-slide\">\r\n");
      out.write("                            <figure class=\"product-image\">\r\n");
      out.write("                                <img src=\"assets/images/products/popup/2-440x494.jpg\"\r\n");
      out.write("                                     data-zoom-image=\"assets/images/products/popup/2-800x900.jpg\"\r\n");
      out.write("                                     alt=\"Water Boil Black Utensil\" width=\"800\" height=\"900\">\r\n");
      out.write("                            </figure>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"swiper-slide\">\r\n");
      out.write("                            <figure class=\"product-image\">\r\n");
      out.write("                                <img src=\"assets/images/products/popup/3-440x494.jpg\"\r\n");
      out.write("                                     data-zoom-image=\"assets/images/products/popup/3-800x900.jpg\"\r\n");
      out.write("                                     alt=\"Water Boil Black Utensil\" width=\"800\" height=\"900\">\r\n");
      out.write("                            </figure>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"swiper-slide\">\r\n");
      out.write("                            <figure class=\"product-image\">\r\n");
      out.write("                                <img src=\"assets/images/products/popup/4-440x494.jpg\"\r\n");
      out.write("                                     data-zoom-image=\"assets/images/products/popup/4-800x900.jpg\"\r\n");
      out.write("                                     alt=\"Water Boil Black Utensil\" width=\"800\" height=\"900\">\r\n");
      out.write("                            </figure>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"swiper-button-next\"></button>\r\n");
      out.write("                    <button class=\"swiper-button-prev\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"product-thumbs-wrap swiper-container\" data-swiper-options=\"{\r\n");
      out.write("                        'navigation': {\r\n");
      out.write("                            'nextEl': '.swiper-button-next',\r\n");
      out.write("                            'prevEl': '.swiper-button-prev'\r\n");
      out.write("                        }\r\n");
      out.write("                    }\">\r\n");
      out.write("                    <div class=\"product-thumbs swiper-wrapper row cols-4 gutter-sm\">\r\n");
      out.write("                        <div class=\"product-thumb swiper-slide\">\r\n");
      out.write("                            <img src=\"assets/images/products/popup/1-103x116.jpg\" alt=\"Product Thumb\" width=\"103\"\r\n");
      out.write("                                 height=\"116\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product-thumb swiper-slide\">\r\n");
      out.write("                            <img src=\"assets/images/products/popup/2-103x116.jpg\" alt=\"Product Thumb\" width=\"103\"\r\n");
      out.write("                                 height=\"116\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product-thumb swiper-slide\">\r\n");
      out.write("                            <img src=\"assets/images/products/popup/3-103x116.jpg\" alt=\"Product Thumb\" width=\"103\"\r\n");
      out.write("                                 height=\"116\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product-thumb swiper-slide\">\r\n");
      out.write("                            <img src=\"assets/images/products/popup/4-103x116.jpg\" alt=\"Product Thumb\" width=\"103\"\r\n");
      out.write("                                 height=\"116\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"swiper-button-next\"></button>\r\n");
      out.write("                    <button class=\"swiper-button-prev\"></button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"col-md-6 overflow-hidden p-relative\">\r\n");
      out.write("            <div class=\"product-details scrollable pl-0\">\r\n");
      out.write("                <h2 class=\"product-title\">Electronics Black Wrist Watch</h2>\r\n");
      out.write("                <div class=\"product-bm-wrapper\">\r\n");
      out.write("                    <figure class=\"brand\">\r\n");
      out.write("                        <img src=\"assets/images/products/brand/brand-1.jpg\" alt=\"Brand\" width=\"102\" height=\"48\" />\r\n");
      out.write("                    </figure>\r\n");
      out.write("                    <div class=\"product-meta\">\r\n");
      out.write("                        <div class=\"product-categories\">\r\n");
      out.write("                            Category:\r\n");
      out.write("                            <span class=\"product-category\"><a href=\"#\">Electronics</a></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"product-sku\">\r\n");
      out.write("                            SKU: <span>MS46891340</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <hr class=\"product-divider\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"product-price\">$40.00</div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"ratings-container\">\r\n");
      out.write("                    <div class=\"ratings-full\">\r\n");
      out.write("                        <span class=\"ratings\" style=\"width: 80%;\"></span>\r\n");
      out.write("                        <span class=\"tooltiptext tooltip-top\"></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#\" class=\"rating-reviews\">(3 Reviews)</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"product-short-desc\">\r\n");
      out.write("                    <ul class=\"list-type-check list-style-none\">\r\n");
      out.write("                        <li>Ultrices eros in cursus turpis massa cursus mattis.</li>\r\n");
      out.write("                        <li>Volutpat ac tincidunt vitae semper quis lectus.</li>\r\n");
      out.write("                        <li>Aliquam id diam maecenas ultricies mi eget mauris.</li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <hr class=\"product-divider\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"product-form product-variation-form product-color-swatch\">\r\n");
      out.write("                    <label>Color:</label>\r\n");
      out.write("                    <div class=\"d-flex align-items-center product-variations\">\r\n");
      out.write("                        <a href=\"#\" class=\"color\" style=\"background-color: #ffcc01\"></a>\r\n");
      out.write("                        <a href=\"#\" class=\"color\" style=\"background-color: #ca6d00;\"></a>\r\n");
      out.write("                        <a href=\"#\" class=\"color\" style=\"background-color: #1c93cb;\"></a>\r\n");
      out.write("                        <a href=\"#\" class=\"color\" style=\"background-color: #ccc;\"></a>\r\n");
      out.write("                        <a href=\"#\" class=\"color\" style=\"background-color: #333;\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"product-form product-variation-form product-size-swatch\">\r\n");
      out.write("                    <label class=\"mb-1\">Size:</label>\r\n");
      out.write("                    <div class=\"flex-wrap d-flex align-items-center product-variations\">\r\n");
      out.write("                        <a href=\"#\" class=\"size\">Small</a>\r\n");
      out.write("                        <a href=\"#\" class=\"size\">Medium</a>\r\n");
      out.write("                        <a href=\"#\" class=\"size\">Large</a>\r\n");
      out.write("                        <a href=\"#\" class=\"size\">Extra Large</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <a href=\"#\" class=\"product-variation-clean\">Clean All</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"product-variation-price\">\r\n");
      out.write("                    <span></span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"product-form\">\r\n");
      out.write("                    <div class=\"product-qty-form\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <input class=\"quantity form-control\" type=\"number\" min=\"1\" max=\"10000000\">\r\n");
      out.write("                            <button class=\"quantity-plus w-icon-plus\"></button>\r\n");
      out.write("                            <button class=\"quantity-minus w-icon-minus\"></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"btn btn-primary btn-cart\">\r\n");
      out.write("                        <i class=\"w-icon-cart\"></i>\r\n");
      out.write("                        <span>Add to Cart</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"social-links-wrapper\">\r\n");
      out.write("                    <div class=\"social-links\">\r\n");
      out.write("                        <div class=\"social-icons social-no-color border-thin\">\r\n");
      out.write("                            <a href=\"#\" class=\"social-icon social-facebook w-icon-facebook\"></a>\r\n");
      out.write("                            <a href=\"#\" class=\"social-icon social-twitter w-icon-twitter\"></a>\r\n");
      out.write("                            <a href=\"#\" class=\"social-icon social-pinterest fab fa-pinterest-p\"></a>\r\n");
      out.write("                            <a href=\"#\" class=\"social-icon social-whatsapp fab fa-whatsapp\"></a>\r\n");
      out.write("                            <a href=\"#\" class=\"social-icon social-youtube fab fa-linkedin-in\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <span class=\"divider d-xs-show\"></span>\r\n");
      out.write("                    <div class=\"product-link-wrapper d-flex\">\r\n");
      out.write("                        <a href=\"#\" class=\"btn-product-icon btn-wishlist w-icon-heart\"><span></span></a>\r\n");
      out.write("                        <a href=\"#\"\r\n");
      out.write("                           class=\"btn-product-icon btn-compare btn-icon-left w-icon-compare\"><span></span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End of Quick view -->\r\n");
      out.write("\r\n");
      out.write("<!-- Plugin JS File -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/sticky/sticky.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/jquery.plugin/jquery.plugin.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/nouislider/nouislider.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/imagesloaded/imagesloaded.pkgd.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/zoom/jquery.zoom.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/jquery.countdown/jquery.countdown.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/vendor/magnific-popup/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Main JS -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/main.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fblock_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:block
    lk.callidora.jsp.inheritance.BlockTag _jspx_th_layout_005fblock_005f0 = new lk.callidora.jsp.inheritance.BlockTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fblock_005f0);
    try {
      _jspx_th_layout_005fblock_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/layouts/other.jsp(60,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fblock_005f0.setName("content");
      _jspx_th_layout_005fblock_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fblock_005f0, null));
      _jspx_th_layout_005fblock_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fblock_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
