/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-24 05:42:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class footer1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<footer class=\"footer appear-animate\" data-animation-options=\"{\r\n");
      out.write("            'name': 'fadeIn'\r\n");
      out.write("        }\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"footer-top\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-4 col-sm-6\">\r\n");
      out.write("                    <div class=\"widget widget-about\">\r\n");
      out.write("                        <a href=\"demo1.html\" class=\"logo-footer\">\r\n");
      out.write("                            <img src=\"assets/images/logo_footer.png\" alt=\"logo-footer\" width=\"144\"\r\n");
      out.write("                                 height=\"45\" />\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"widget-body\">\r\n");
      out.write("                            <p class=\"widget-about-title\">Got Question? Call us 24/7</p>\r\n");
      out.write("                            <a href=\"tel:18005707777\" class=\"widget-about-call\">1-800-570-7777</a>\r\n");
      out.write("                            <p class=\"widget-about-desc\">Register now to get updates on pronot get up icons\r\n");
      out.write("                                & coupons ster now toon.\r\n");
      out.write("                            </p>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"social-icons social-icons-colored\">\r\n");
      out.write("                                <a href=\"#\" class=\"social-icon social-facebook w-icon-facebook\"></a>\r\n");
      out.write("                                <a href=\"#\" class=\"social-icon social-twitter w-icon-twitter\"></a>\r\n");
      out.write("                                <a href=\"#\" class=\"social-icon social-instagram w-icon-instagram\"></a>\r\n");
      out.write("                                <a href=\"#\" class=\"social-icon social-youtube w-icon-youtube\"></a>\r\n");
      out.write("                                <a href=\"#\" class=\"social-icon social-pinterest w-icon-pinterest\"></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"widget\">\r\n");
      out.write("                        <h3 class=\"widget-title\">Company</h3>\r\n");
      out.write("                        <ul class=\"widget-body\">\r\n");
      out.write("                            <li><a href=\"about-us.html\">About Us</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Team Member</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Career</a></li>\r\n");
      out.write("                            <li><a href=\"contact-us.html\">Contact Us</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Affilate</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Order History</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"widget\">\r\n");
      out.write("                        <h4 class=\"widget-title\">My Account</h4>\r\n");
      out.write("                        <ul class=\"widget-body\">\r\n");
      out.write("                            <li><a href=\"#\">Track My Order</a></li>\r\n");
      out.write("                            <li><a href=\"cart.html\">View Cart</a></li>\r\n");
      out.write("                            <li><a href=\"login.html\">Sign In</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Help</a></li>\r\n");
      out.write("                            <li><a href=\"wishlist.html\">My Wishlist</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Privacy Policy</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-3 col-sm-6\">\r\n");
      out.write("                    <div class=\"widget\">\r\n");
      out.write("                        <h4 class=\"widget-title\">Customer Service</h4>\r\n");
      out.write("                        <ul class=\"widget-body\">\r\n");
      out.write("                            <li><a href=\"#\">Payment Methods</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Money-back guarantee!</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Product Returns</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Support Center</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Shipping</a></li>\r\n");
      out.write("                            <li><a href=\"#\">Term and Conditions</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-middle\">\r\n");
      out.write("            <div class=\"widget widget-category\">\r\n");
      out.write("                <div class=\"category-box\">\r\n");
      out.write("                    <h6 class=\"category-name\">Consumer Electric:</h6>\r\n");
      out.write("                    <a href=\"#\">TV Television</a>\r\n");
      out.write("                    <a href=\"#\">Air Condition</a>\r\n");
      out.write("                    <a href=\"#\">Refrigerator</a>\r\n");
      out.write("                    <a href=\"#\">Washing Machine</a>\r\n");
      out.write("                    <a href=\"#\">Audio Speaker</a>\r\n");
      out.write("                    <a href=\"#\">Security Camera</a>\r\n");
      out.write("                    <a href=\"#\">View All</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"category-box\">\r\n");
      out.write("                    <h6 class=\"category-name\">Clothing & Apparel:</h6>\r\n");
      out.write("                    <a href=\"#\">Men's T-shirt</a>\r\n");
      out.write("                    <a href=\"#\">Dresses</a>\r\n");
      out.write("                    <a href=\"#\">Men's Sneacker</a>\r\n");
      out.write("                    <a href=\"#\">Leather Backpack</a>\r\n");
      out.write("                    <a href=\"#\">Watches</a>\r\n");
      out.write("                    <a href=\"#\">Jeans</a>\r\n");
      out.write("                    <a href=\"#\">Sunglasses</a>\r\n");
      out.write("                    <a href=\"#\">Boots</a>\r\n");
      out.write("                    <a href=\"#\">Rayban</a>\r\n");
      out.write("                    <a href=\"#\">Acccessories</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"category-box\">\r\n");
      out.write("                    <h6 class=\"category-name\">Home, Garden & Kitchen:</h6>\r\n");
      out.write("                    <a href=\"#\">Sofa</a>\r\n");
      out.write("                    <a href=\"#\">Chair</a>\r\n");
      out.write("                    <a href=\"#\">Bed Room</a>\r\n");
      out.write("                    <a href=\"#\">Living Room</a>\r\n");
      out.write("                    <a href=\"#\">Cookware</a>\r\n");
      out.write("                    <a href=\"#\">Utensil</a>\r\n");
      out.write("                    <a href=\"#\">Blender</a>\r\n");
      out.write("                    <a href=\"#\">Garden Equipments</a>\r\n");
      out.write("                    <a href=\"#\">Decor</a>\r\n");
      out.write("                    <a href=\"#\">Library</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"category-box\">\r\n");
      out.write("                    <h6 class=\"category-name\">Health & Beauty:</h6>\r\n");
      out.write("                    <a href=\"#\">Skin Care</a>\r\n");
      out.write("                    <a href=\"#\">Body Shower</a>\r\n");
      out.write("                    <a href=\"#\">Makeup</a>\r\n");
      out.write("                    <a href=\"#\">Hair Care</a>\r\n");
      out.write("                    <a href=\"#\">Lipstick</a>\r\n");
      out.write("                    <a href=\"#\">Perfume</a>\r\n");
      out.write("                    <a href=\"#\">View all</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"category-box\">\r\n");
      out.write("                    <h6 class=\"category-name\">Jewelry & Watches:</h6>\r\n");
      out.write("                    <a href=\"#\">Necklace</a>\r\n");
      out.write("                    <a href=\"#\">Pendant</a>\r\n");
      out.write("                    <a href=\"#\">Diamond Ring</a>\r\n");
      out.write("                    <a href=\"#\">Silver Earing</a>\r\n");
      out.write("                    <a href=\"#\">Leather Watcher</a>\r\n");
      out.write("                    <a href=\"#\">Rolex</a>\r\n");
      out.write("                    <a href=\"#\">Gucci</a>\r\n");
      out.write("                    <a href=\"#\">Australian Opal</a>\r\n");
      out.write("                    <a href=\"#\">Ammolite</a>\r\n");
      out.write("                    <a href=\"#\">Sun Pyrite</a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"category-box\">\r\n");
      out.write("                    <h6 class=\"category-name\">Computer & Technologies:</h6>\r\n");
      out.write("                    <a href=\"#\">Laptop</a>\r\n");
      out.write("                    <a href=\"#\">iMac</a>\r\n");
      out.write("                    <a href=\"#\">Smartphone</a>\r\n");
      out.write("                    <a href=\"#\">Tablet</a>\r\n");
      out.write("                    <a href=\"#\">Apple</a>\r\n");
      out.write("                    <a href=\"#\">Asus</a>\r\n");
      out.write("                    <a href=\"#\">Drone</a>\r\n");
      out.write("                    <a href=\"#\">Wireless Speaker</a>\r\n");
      out.write("                    <a href=\"#\">Game Controller</a>\r\n");
      out.write("                    <a href=\"#\">View all</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"footer-bottom\">\r\n");
      out.write("            <div class=\"footer-left\">\r\n");
      out.write("                <p class=\"copyright\">Copyright Â© 2021 Wolmart Store. All Rights Reserved.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"footer-right\">\r\n");
      out.write("                <span class=\"payment-label mr-lg-8\">We're using safe payment for</span>\r\n");
      out.write("                <figure class=\"payment\">\r\n");
      out.write("                    <img src=\"assets/images/payment.png\" alt=\"payment\" width=\"159\" height=\"25\" />\r\n");
      out.write("                </figure>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
