/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-26 07:58:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- Start of Header -->\r\n");
      out.write("<header class=\"header\">\r\n");
      out.write("    <div class=\"header-top\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"header-left\">\r\n");
      out.write("                <p class=\"welcome-msg\">Welcome to Luminary Clothing Store</p>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-right\">\r\n");
      out.write("                <div class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#currency\">USD</a>\r\n");
      out.write("                    <div class=\"dropdown-box\">\r\n");
      out.write("                        <a href=\"#USD\">USD</a>\r\n");
      out.write("                        <a href=\"#EUR\">EUR</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End of DropDown Menu -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"dropdown\">\r\n");
      out.write("                    <a href=\"#language\"><img src=\"assets/images/flags/eng.png\" alt=\"ENG Flag\" width=\"14\"\r\n");
      out.write("                                             height=\"8\" class=\"dropdown-image\" /> ENG</a>\r\n");
      out.write("                    <div class=\"dropdown-box\">\r\n");
      out.write("                        <a href=\"#ENG\">\r\n");
      out.write("                            <img src=\"assets/images/flags/eng.png\" alt=\"ENG Flag\" width=\"14\" height=\"8\"\r\n");
      out.write("                                 class=\"dropdown-image\" />\r\n");
      out.write("                            ENG\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"#FRA\">\r\n");
      out.write("                            <img src=\"assets/images/flags/fra.png\" alt=\"FRA Flag\" width=\"14\" height=\"8\"\r\n");
      out.write("                                 class=\"dropdown-image\" />\r\n");
      out.write("                            FRA\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End of Dropdown Menu -->\r\n");
      out.write("                <span class=\"divider d-lg-show\"></span>\r\n");
      out.write("                <a href=\"blog.html\" class=\"d-lg-show\">Blog</a>\r\n");
      out.write("                <a href=\"contact-us.html\" class=\"d-lg-show\">Contact Us</a>\r\n");
      out.write("                <a href=\"my-account.html\" class=\"d-lg-show\">My Account</a>\r\n");
      out.write("                <a href=\"/luminary/login\" class=\"d-lg-show login\"><i\r\n");
      out.write("                        class=\"w-icon-account\"></i>Sign In</a>\r\n");
      out.write("                <span class=\"delimiter d-lg-show\">/</span>\r\n");
      out.write("                <a href=\"/luminary/login\" class=\"ml-0 d-lg-show login\">Register</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End of Header Top -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"header-middle\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"header-left mr-md-4\">\r\n");
      out.write("                <a href=\"#\" class=\"mobile-menu-toggle w-icon-hamburger\" aria-label=\"menu-toggle\">\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"/luminary/\" class=\"logo ml-lg-0\">\r\n");
      out.write("                    <img src=\"assets/images/demos/demo3/logo.png\" alt=\"logo\" width=\"144\" height=\"45\" />\r\n");
      out.write("                </a>\r\n");
      out.write("                <form method=\"get\" action=\"/luminary/search\" class=\"header-search hs-expanded hs-round d-none d-md-flex input-wrapper\">\r\n");
      out.write("                    <div class=\"select-box\">\r\n");
      out.write("                        <select id=\"category\" name=\"category\" class=\"pb-0\">\r\n");
      out.write("                            <option value=\"0\">All Categories</option>\r\n");
      out.write("                            <option value=\"1\">MEN</option>\r\n");
      out.write("                            <option value=\"2\">WOMEN</option>\r\n");
      out.write("                            <option value=\"3\">KIDS</option>\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" name=\"search\" id=\"search\"\r\n");
      out.write("                           placeholder=\"Search in...\" required />\r\n");
      out.write("                    <button class=\"btn btn-search\" type=\"submit\"><i class=\"w-icon-search\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"header-right ml-4\">\r\n");
      out.write("                <div class=\"header-call d-xs-show d-lg-flex align-items-center\">\r\n");
      out.write("                    <a href=\"tel:#\" class=\"w-icon-call\"></a>\r\n");
      out.write("                    <div class=\"call-info d-lg-show\">\r\n");
      out.write("                        <h4 class=\"chat font-weight-normal font-size-md text-normal ls-normal text-light mb-0\">\r\n");
      out.write("                            <a href=\"mailto:#\" class=\"text-capitalize\">Call Us Now</a> :</h4>\r\n");
      out.write("                        <a href=\"tel:#\" class=\"phone-number font-weight-bolder ls-50\">0(800)123-456</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a class=\"wishlist label-down link d-xs-show\" href=\"wishlist.html\">\r\n");
      out.write("                    <i class=\"w-icon-heart\"></i>\r\n");
      out.write("                    <span class=\"wishlist-label d-lg-show\">Wishlist</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a class=\"compare label-down link d-xs-show\" href=\"compare.html\">\r\n");
      out.write("                    <i class=\"w-icon-compare\"></i>\r\n");
      out.write("                    <span class=\"compare-label d-lg-show\">Compare</span>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"dropdown cart-dropdown cart-offcanvas mr-0 mr-lg-2\">\r\n");
      out.write("                    <div class=\"cart-overlay\"></div>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("cart\">\r\n");
      out.write("                        <i class=\"w-icon-cart\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    <div class=\"dropdown-box\">\r\n");
      out.write("                        <div class=\"cart-header\">\r\n");
      out.write("                            <span>Shopping Cart</span>\r\n");
      out.write("                            <a href=\"#\" class=\"btn-close\">Close<i class=\"w-icon-long-arrow-right\"></i></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"products\">\r\n");
      out.write("                            <div class=\"product product-cart\">\r\n");
      out.write("                                <div class=\"product-detail\">\r\n");
      out.write("                                    <a href=\"product-default.html\" class=\"product-name\">Beige knitted\r\n");
      out.write("                                        elas<br>tic\r\n");
      out.write("                                        runner shoes</a>\r\n");
      out.write("                                    <div class=\"price-box\">\r\n");
      out.write("                                        <span class=\"product-quantity\">1</span>\r\n");
      out.write("                                        <span class=\"product-price\">$25.68</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <figure class=\"product-media\">\r\n");
      out.write("                                    <a href=\"product-default.html\">\r\n");
      out.write("                                        <img src=\"assets/images/cart/product-1.jpg\" alt=\"product\" height=\"84\"\r\n");
      out.write("                                             width=\"94\" />\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </figure>\r\n");
      out.write("                                <button class=\"btn btn-link btn-close\" aria-label=\"button\">\r\n");
      out.write("                                    <i class=\"fas fa-times\"></i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"product product-cart\">\r\n");
      out.write("                                <div class=\"product-detail\">\r\n");
      out.write("                                    <a href=\"product-default.html\" class=\"product-name\">Blue utility\r\n");
      out.write("                                        pina<br>fore\r\n");
      out.write("                                        denim dress</a>\r\n");
      out.write("                                    <div class=\"price-box\">\r\n");
      out.write("                                        <span class=\"product-quantity\">1</span>\r\n");
      out.write("                                        <span class=\"product-price\">$32.99</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <figure class=\"product-media\">\r\n");
      out.write("                                    <a href=\"product-default.html\">\r\n");
      out.write("                                        <img src=\"assets/images/cart/product-2.jpg\" alt=\"product\" width=\"84\"\r\n");
      out.write("                                             height=\"94\" />\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </figure>\r\n");
      out.write("                                <button class=\"btn btn-link btn-close\" aria-label=\"button\">\r\n");
      out.write("                                    <i class=\"fas fa-times\"></i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"cart-total\">\r\n");
      out.write("                            <label>Subtotal:</label>\r\n");
      out.write("                            <span class=\"price\">$58.67</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"cart-action\">\r\n");
      out.write("                            <a href=\"cart.html\" class=\"btn btn-dark btn-outline btn-rounded\">View Cart</a>\r\n");
      out.write("                            <a href=\"checkout.html\" class=\"btn btn-primary  btn-rounded\">Checkout</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- End of Dropdown Box -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End of Header Middle -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"header-bottom sticky-content fix-top sticky-header has-dropdown\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"inner-wrap\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</header>\r\n");
      out.write("<!-- End of Header -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
