/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-24 10:59:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.include;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class header1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<header class=\"header header-border\">\r\n");
      out.write("  <div class=\"header-top\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"header-left\">\r\n");
      out.write("        <p class=\"welcome-msg\">Welcome to Luminary Clothing Store</p>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"header-right\">\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("          <a href=\"#currency\">USD</a>\r\n");
      out.write("          <div class=\"dropdown-box\">\r\n");
      out.write("            <a href=\"#USD\">USD</a>\r\n");
      out.write("            <a href=\"#EUR\">EUR</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of DropDown Menu -->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"dropdown\">\r\n");
      out.write("          <a href=\"#language\"><img src=\"assets/images/flags/eng.png\" alt=\"ENG Flag\" width=\"14\"\r\n");
      out.write("                                   height=\"8\" class=\"dropdown-image\" /> ENG</a>\r\n");
      out.write("          <div class=\"dropdown-box\">\r\n");
      out.write("            <a href=\"#ENG\">\r\n");
      out.write("              <img src=\"assets/images/flags/eng.png\" alt=\"ENG Flag\" width=\"14\" height=\"8\"\r\n");
      out.write("                   class=\"dropdown-image\" />\r\n");
      out.write("              ENG\r\n");
      out.write("            </a>\r\n");
      out.write("            <a href=\"#FRA\">\r\n");
      out.write("              <img src=\"assets/images/flags/fra.png\" alt=\"FRA Flag\" width=\"14\" height=\"8\"\r\n");
      out.write("                   class=\"dropdown-image\" />\r\n");
      out.write("              FRA\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of Dropdown Menu -->\r\n");
      out.write("        <span class=\"divider d-lg-show\"></span>\r\n");
      out.write("        <a href=\"blog.html\" class=\"d-lg-show\">Blog</a>\r\n");
      out.write("        <a href=\"contact-us.html\" class=\"d-lg-show\">Contact Us</a>\r\n");
      out.write("        <a href=\"my-account.html\" class=\"d-lg-show\">My Account</a>\r\n");
      out.write("        <a href=\"assets/ajax/login.html\" class=\"d-lg-show login sign-in\"><i\r\n");
      out.write("                class=\"w-icon-account\"></i>Sign In</a>\r\n");
      out.write("        <span class=\"delimiter d-lg-show\">/</span>\r\n");
      out.write("        <a href=\"assets/ajax/login.html\" class=\"ml-0 d-lg-show login register\">Register</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- End of Header Top -->\r\n");
      out.write("\r\n");
      out.write("  <div class=\"header-middle\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"header-left mr-md-4\">\r\n");
      out.write("        <a href=\"#\" class=\"mobile-menu-toggle  w-icon-hamburger\" aria-label=\"menu-toggle\">\r\n");
      out.write("        </a>\r\n");
      out.write("        <a href=\"demo1.html\" class=\"logo ml-lg-0\">\r\n");
      out.write("          <img src=\"assets/images/demos/demo3/logo.png\" alt=\"logo\" width=\"144\" height=\"45\" />\r\n");
      out.write("        </a>\r\n");
      out.write("        <form method=\"get\" action=\"#\" class=\"header-search hs-expanded hs-round d-none d-md-flex input-wrapper\">\r\n");
      out.write("          <div class=\"select-box\">\r\n");
      out.write("            <select id=\"category\" name=\"category\">\r\n");
      out.write("              <option value=\"\">All Categories</option>\r\n");
      out.write("              <option value=\"4\">Fashion</option>\r\n");
      out.write("              <option value=\"5\">Furniture</option>\r\n");
      out.write("              <option value=\"6\">Shoes</option>\r\n");
      out.write("              <option value=\"7\">Sports</option>\r\n");
      out.write("              <option value=\"8\">Games</option>\r\n");
      out.write("              <option value=\"9\">Computers</option>\r\n");
      out.write("              <option value=\"10\">Electronics</option>\r\n");
      out.write("              <option value=\"11\">Kitchen</option>\r\n");
      out.write("              <option value=\"12\">Clothing</option>\r\n");
      out.write("            </select>\r\n");
      out.write("          </div>\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" name=\"search\" id=\"search\"\r\n");
      out.write("                 placeholder=\"Search in...\" required />\r\n");
      out.write("          <button class=\"btn btn-search\" type=\"submit\"><i class=\"w-icon-search\"></i>\r\n");
      out.write("          </button>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"header-right ml-4\">\r\n");
      out.write("        <div class=\"header-call d-xs-show d-lg-flex align-items-center\">\r\n");
      out.write("          <a href=\"tel:#\" class=\"w-icon-call\"></a>\r\n");
      out.write("          <div class=\"call-info d-lg-show\">\r\n");
      out.write("            <h4 class=\"chat font-weight-normal font-size-md text-normal ls-normal text-light mb-0\">\r\n");
      out.write("              <a href=\"mailto:#\" class=\"text-capitalize\">Live Chat</a> or :</h4>\r\n");
      out.write("            <a href=\"tel:#\" class=\"phone-number font-weight-bolder ls-50\">0(800)123-456</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"wishlist label-down link d-xs-show\" href=\"wishlist.html\">\r\n");
      out.write("          <i class=\"w-icon-heart\"></i>\r\n");
      out.write("          <span class=\"wishlist-label d-lg-show\">Wishlist</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"compare label-down link d-xs-show\" href=\"compare.html\">\r\n");
      out.write("          <i class=\"w-icon-compare\"></i>\r\n");
      out.write("          <span class=\"compare-label d-lg-show\">Compare</span>\r\n");
      out.write("        </a>\r\n");
      out.write("        <div class=\"dropdown cart-dropdown cart-offcanvas mr-0 mr-lg-2\">\r\n");
      out.write("          <div class=\"cart-overlay\"></div>\r\n");
      out.write("          <a href=\"#\" class=\"cart-toggle label-down link\">\r\n");
      out.write("            <i class=\"w-icon-cart\">\r\n");
      out.write("              <span class=\"cart-count\">2</span>\r\n");
      out.write("            </i>\r\n");
      out.write("            <span class=\"cart-label\">Cart</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <div class=\"dropdown-box\">\r\n");
      out.write("            <div class=\"cart-header\">\r\n");
      out.write("              <span>Shopping Cart</span>\r\n");
      out.write("              <a href=\"#\" class=\"btn-close\">Close<i class=\"w-icon-long-arrow-right\"></i></a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"products\">\r\n");
      out.write("              <div class=\"product product-cart\">\r\n");
      out.write("                <div class=\"product-detail\">\r\n");
      out.write("                  <a href=\"product-default.html\" class=\"product-name\">Beige knitted\r\n");
      out.write("                    elas<br>tic\r\n");
      out.write("                    runner shoes</a>\r\n");
      out.write("                  <div class=\"price-box\">\r\n");
      out.write("                    <span class=\"product-quantity\">1</span>\r\n");
      out.write("                    <span class=\"product-price\">$25.68</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <figure class=\"product-media\">\r\n");
      out.write("                  <a href=\"product-default.html\">\r\n");
      out.write("                    <img src=\"assets/images/cart/product-1.jpg\" alt=\"product\" height=\"84\"\r\n");
      out.write("                         width=\"94\" />\r\n");
      out.write("                  </a>\r\n");
      out.write("                </figure>\r\n");
      out.write("                <button class=\"btn btn-link btn-close\" aria-label=\"button\">\r\n");
      out.write("                  <i class=\"fas fa-times\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"product product-cart\">\r\n");
      out.write("                <div class=\"product-detail\">\r\n");
      out.write("                  <a href=\"product-default.html\" class=\"product-name\">Blue utility\r\n");
      out.write("                    pina<br>fore\r\n");
      out.write("                    denim dress</a>\r\n");
      out.write("                  <div class=\"price-box\">\r\n");
      out.write("                    <span class=\"product-quantity\">1</span>\r\n");
      out.write("                    <span class=\"product-price\">$32.99</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <figure class=\"product-media\">\r\n");
      out.write("                  <a href=\"product-default.html\">\r\n");
      out.write("                    <img src=\"assets/images/cart/product-2.jpg\" alt=\"product\" width=\"84\"\r\n");
      out.write("                         height=\"94\" />\r\n");
      out.write("                  </a>\r\n");
      out.write("                </figure>\r\n");
      out.write("                <button class=\"btn btn-link btn-close\" aria-label=\"button\">\r\n");
      out.write("                  <i class=\"fas fa-times\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cart-total\">\r\n");
      out.write("              <label>Subtotal:</label>\r\n");
      out.write("              <span class=\"price\">$58.67</span>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"cart-action\">\r\n");
      out.write("              <a href=\"cart.html\" class=\"btn btn-dark btn-outline btn-rounded\">View Cart</a>\r\n");
      out.write("              <a href=\"checkout.html\" class=\"btn btn-primary  btn-rounded\">Checkout</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- End of Dropdown Box -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- End of Header Middle -->\r\n");
      out.write("\r\n");
      out.write("  <div class=\"header-bottom sticky-content fix-top sticky-header\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("      <div class=\"inner-wrap\">\r\n");
      out.write("        <div class=\"header-left\">\r\n");
      out.write("          <div class=\"dropdown category-dropdown has-border\" data-visible=\"true\">\r\n");
      out.write("            <a href=\"#\" class=\"category-toggle\" role=\"button\" data-toggle=\"dropdown\"\r\n");
      out.write("               aria-haspopup=\"true\" aria-expanded=\"true\" data-display=\"static\"\r\n");
      out.write("               title=\"Browse Categories\">\r\n");
      out.write("              <i class=\"w-icon-category\"></i>\r\n");
      out.write("              <span>Browse Categories</span>\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"dropdown-box\">\r\n");
      out.write("              <ul class=\"menu vertical-menu category-menu\">\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                    <i class=\"w-icon-tshirt2\"></i>Fashion\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <ul class=\"megamenu\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <h4 class=\"menu-title\">Women</h4>\r\n");
      out.write("                      <hr class=\"divider\">\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">New Arrivals</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Best Sellers</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Trending</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Clothing</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Shoes</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Bags</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Accessories</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Jewlery &\r\n");
      out.write("                          Watches</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Sale</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <h4 class=\"menu-title\">Men</h4>\r\n");
      out.write("                      <hr class=\"divider\">\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">New Arrivals</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Best Sellers</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Trending</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Clothing</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Shoes</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Bags</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Accessories</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Jewlery &\r\n");
      out.write("                          Watches</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <div class=\"banner-fixed menu-banner menu-banner2\">\r\n");
      out.write("                        <figure>\r\n");
      out.write("                          <img src=\"assets/images/menu/banner-2.jpg\" alt=\"Menu Banner\"\r\n");
      out.write("                               width=\"235\" height=\"347\" />\r\n");
      out.write("                        </figure>\r\n");
      out.write("                        <div class=\"banner-content\">\r\n");
      out.write("                          <div class=\"banner-price-info mb-1 ls-normal\">Get up to\r\n");
      out.write("                            <strong\r\n");
      out.write("                                    class=\"text-primary text-uppercase\">20%Off</strong>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <h3 class=\"banner-title ls-normal\">Hot Sales</h3>\r\n");
      out.write("                          <a href=\"shop-banner-sidebar.html\"\r\n");
      out.write("                             class=\"btn btn-dark btn-sm btn-link btn-slide-right btn-icon-right\">\r\n");
      out.write("                            Shop Now<i class=\"w-icon-long-arrow-right\"></i>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                    <i class=\"w-icon-home\"></i>Home & Garden\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <ul class=\"megamenu\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <h4 class=\"menu-title\">Bedroom</h4>\r\n");
      out.write("                      <hr class=\"divider\">\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Beds, Frames &\r\n");
      out.write("                          Bases</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Dressers</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Nightstands</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Kid's Beds &\r\n");
      out.write("                          Headboards</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Armoires</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("\r\n");
      out.write("                      <h4 class=\"menu-title mt-1\">Living Room</h4>\r\n");
      out.write("                      <hr class=\"divider\">\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Coffee Tables</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Chairs</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Tables</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Futons & Sofa\r\n");
      out.write("                          Beds</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Cabinets &\r\n");
      out.write("                          Chests</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <h4 class=\"menu-title\">Office</h4>\r\n");
      out.write("                      <hr class=\"divider\">\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Office Chairs</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Desks</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Bookcases</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">File Cabinets</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Breakroom\r\n");
      out.write("                          Tables</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("\r\n");
      out.write("                      <h4 class=\"menu-title mt-1\">Kitchen & Dining</h4>\r\n");
      out.write("                      <hr class=\"divider\">\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Dining Sets</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Kitchen Storage\r\n");
      out.write("                          Cabinets</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Bashers Racks</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Dining Chairs</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Dining Room\r\n");
      out.write("                          Tables</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Bar Stools</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <div class=\"menu-banner banner-fixed menu-banner3\">\r\n");
      out.write("                        <figure>\r\n");
      out.write("                          <img src=\"assets/images/menu/banner-3.jpg\" alt=\"Menu Banner\"\r\n");
      out.write("                               width=\"235\" height=\"461\" />\r\n");
      out.write("                        </figure>\r\n");
      out.write("                        <div class=\"banner-content\">\r\n");
      out.write("                          <h4\r\n");
      out.write("                                  class=\"banner-subtitle font-weight-normal text-white mb-1\">\r\n");
      out.write("                            Restroom</h4>\r\n");
      out.write("                          <h3\r\n");
      out.write("                                  class=\"banner-title font-weight-bolder text-white ls-normal\">\r\n");
      out.write("                            Furniture Sale</h3>\r\n");
      out.write("                          <div\r\n");
      out.write("                                  class=\"banner-price-info text-white font-weight-normal ls-25\">\r\n");
      out.write("                            Up to <span\r\n");
      out.write("                                  class=\"text-secondary text-uppercase font-weight-bold\">25%\r\n");
      out.write("                                                                    Off</span></div>\r\n");
      out.write("                          <a href=\"shop-banner-sidebar.html\"\r\n");
      out.write("                             class=\"btn btn-white btn-link btn-sm btn-slide-right btn-icon-right\">\r\n");
      out.write("                            Shop Now<i class=\"w-icon-long-arrow-right\"></i>\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                    <i class=\"w-icon-electronics\"></i>Electronics\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <ul class=\"megamenu\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <h4 class=\"menu-title\">Laptops &amp; Computers</h4>\r\n");
      out.write("                      <hr class=\"divider\">\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Desktop\r\n");
      out.write("                          Computers</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Monitors</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Laptops</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Hard Drives &amp;\r\n");
      out.write("                          Storage</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Computer\r\n");
      out.write("                          Accessories</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("\r\n");
      out.write("                      <h4 class=\"menu-title mt-1\">TV &amp; Video</h4>\r\n");
      out.write("                      <hr class=\"divider\">\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">TVs</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Home Audio\r\n");
      out.write("                          Speakers</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Projectors</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Media Streaming\r\n");
      out.write("                          Devices</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <h4 class=\"menu-title\">Digital Cameras</h4>\r\n");
      out.write("                      <hr class=\"divider\">\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Digital SLR\r\n");
      out.write("                          Cameras</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Sports & Action\r\n");
      out.write("                          Cameras</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Camera Lenses</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Photo Printer</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Digital Memory\r\n");
      out.write("                          Cards</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("\r\n");
      out.write("                      <h4 class=\"menu-title mt-1\">Cell Phones</h4>\r\n");
      out.write("                      <hr class=\"divider\">\r\n");
      out.write("                      <ul>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Carrier Phones</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Unlocked Phones</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Phone & Cellphone\r\n");
      out.write("                          Cases</a></li>\r\n");
      out.write("                        <li><a href=\"shop-fullwidth-banner.html\">Cellphone\r\n");
      out.write("                          Chargers</a></li>\r\n");
      out.write("                      </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                      <div class=\"menu-banner banner-fixed menu-banner4\">\r\n");
      out.write("                        <figure>\r\n");
      out.write("                          <img src=\"assets/images/menu/banner-4.jpg\" alt=\"Menu Banner\"\r\n");
      out.write("                               width=\"235\" height=\"433\" />\r\n");
      out.write("                        </figure>\r\n");
      out.write("                        <div class=\"banner-content\">\r\n");
      out.write("                          <h4 class=\"banner-subtitle font-weight-normal\">Deals Of The\r\n");
      out.write("                            Week</h4>\r\n");
      out.write("                          <h3 class=\"banner-title text-white\">Save On Smart EarPhone\r\n");
      out.write("                          </h3>\r\n");
      out.write("                          <div\r\n");
      out.write("                                  class=\"banner-price-info text-secondary font-weight-bolder text-uppercase text-secondary\">\r\n");
      out.write("                            20% Off</div>\r\n");
      out.write("                          <a href=\"shop-banner-sidebar.html\"\r\n");
      out.write("                             class=\"btn btn-white btn-outline btn-sm btn-rounded\">Shop\r\n");
      out.write("                            Now</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                    <i class=\"w-icon-furniture\"></i>Furniture\r\n");
      out.write("                  </a>\r\n");
      out.write("                  <ul class=\"megamenu type2\">\r\n");
      out.write("                    <li class=\"row\">\r\n");
      out.write("                      <div class=\"col-md-3 col-lg-3 col-6\">\r\n");
      out.write("                        <h4 class=\"menu-title\">Furniture</h4>\r\n");
      out.write("                        <hr class=\"divider\" />\r\n");
      out.write("                        <ul>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Sofas & Couches</a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Armchairs</a></li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Bed Frames</a></li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Beside Tables</a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Dressing Tables</a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-3 col-lg-3 col-6\">\r\n");
      out.write("                        <h4 class=\"menu-title\">Lighting</h4>\r\n");
      out.write("                        <hr class=\"divider\" />\r\n");
      out.write("                        <ul>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Light Bulbs</a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Lamps</a></li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Celling Lights</a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Wall Lights</a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Bathroom\r\n");
      out.write("                            Lighting</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-3 col-lg-3 col-6\">\r\n");
      out.write("                        <h4 class=\"menu-title\">Home Accessories</h4>\r\n");
      out.write("                        <hr class=\"divider\" />\r\n");
      out.write("                        <ul>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Decorative\r\n");
      out.write("                            Accessories</a></li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Candals &\r\n");
      out.write("                            Holders</a></li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Home Fragrance</a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Mirrors</a></li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Clocks</a></li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-md-3 col-lg-3 col-6\">\r\n");
      out.write("                        <h4 class=\"menu-title\">Garden & Outdoors</h4>\r\n");
      out.write("                        <hr class=\"divider\" />\r\n");
      out.write("                        <ul>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Garden\r\n");
      out.write("                            Furniture</a></li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Lawn Mowers</a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Pressure\r\n");
      out.write("                            Washers</a></li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">All Garden\r\n");
      out.write("                            Tools</a></li>\r\n");
      out.write("                          <li><a href=\"shop-fullwidth-banner.html\">Outdoor Dining</a>\r\n");
      out.write("                          </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"row\">\r\n");
      out.write("                      <div class=\"col-6\">\r\n");
      out.write("                        <div class=\"banner banner-fixed menu-banner5 br-xs\">\r\n");
      out.write("                          <figure>\r\n");
      out.write("                            <img src=\"assets/images/menu/banner-5.jpg\" alt=\"Banner\"\r\n");
      out.write("                                 width=\"410\" height=\"123\"\r\n");
      out.write("                                 style=\"background-color: #D2D2D2;\" />\r\n");
      out.write("                          </figure>\r\n");
      out.write("                          <div class=\"banner-content text-right y-50\">\r\n");
      out.write("                            <h4\r\n");
      out.write("                                    class=\"banner-subtitle font-weight-normal text-default text-capitalize\">\r\n");
      out.write("                              New Arrivals</h4>\r\n");
      out.write("                            <h3\r\n");
      out.write("                                    class=\"banner-title font-weight-bolder text-capitalize ls-normal\">\r\n");
      out.write("                              Amazing Sofa</h3>\r\n");
      out.write("                            <div\r\n");
      out.write("                                    class=\"banner-price-info font-weight-normal ls-normal\">\r\n");
      out.write("                              Starting at <strong>$125.00</strong></div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"col-6\">\r\n");
      out.write("                        <div class=\"banner banner-fixed menu-banner5 br-xs\">\r\n");
      out.write("                          <figure>\r\n");
      out.write("                            <img src=\"assets/images/menu/banner-6.jpg\" alt=\"Banner\"\r\n");
      out.write("                                 width=\"410\" height=\"123\"\r\n");
      out.write("                                 style=\"background-color: #9F9888;\" />\r\n");
      out.write("                          </figure>\r\n");
      out.write("                          <div class=\"banner-content y-50\">\r\n");
      out.write("                            <h4\r\n");
      out.write("                                    class=\"banner-subtitle font-weight-normal text-white text-capitalize\">\r\n");
      out.write("                              Best Seller</h4>\r\n");
      out.write("                            <h3\r\n");
      out.write("                                    class=\"banner-title font-weight-bolder text-capitalize text-white ls-normal\">\r\n");
      out.write("                              Chair &amp; Lamp</h3>\r\n");
      out.write("                            <div\r\n");
      out.write("                                    class=\"banner-price-info font-weight-normal ls-normal text-white\">\r\n");
      out.write("                              From <strong>$165.00</strong></div>\r\n");
      out.write("                          </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                  </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                    <i class=\"w-icon-heartbeat\"></i>Healthy & Beauty\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                    <i class=\"w-icon-gift\"></i>Gift Ideas\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                    <i class=\"w-icon-gamepad\"></i>Toy & Games\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                    <i class=\"w-icon-ice-cream\"></i>Cooking\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                    <i class=\"w-icon-ios\"></i>Smart Phones\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                    <i class=\"w-icon-camera\"></i>Cameras & Photo\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"shop-fullwidth-banner.html\">\r\n");
      out.write("                    <i class=\"w-icon-ruby\"></i>Accessories\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                  <a href=\"shop-banner-sidebar.html\"\r\n");
      out.write("                     class=\"font-weight-bold text-primary text-uppercase ls-25\">\r\n");
      out.write("                    View All Categories<i class=\"w-icon-angle-right\"></i>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("              </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <nav class=\"main-nav\">\r\n");
      out.write("            <ul class=\"menu active-underline\">\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"demo1.html\">Home</a>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"active\">\r\n");
      out.write("                <a href=\"shop-banner-sidebar.html\">Shop</a>\r\n");
      out.write("\r\n");
      out.write("                <!-- Start of Megamenu -->\r\n");
      out.write("                <ul class=\"megamenu\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <h4 class=\"menu-title\">Shop Pages</h4>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li><a href=\"shop-banner-sidebar.html\">Banner With Sidebar</a></li>\r\n");
      out.write("                      <li><a href=\"shop-boxed-banner.html\">Boxed Banner</a></li>\r\n");
      out.write("                      <li><a href=\"shop-fullwidth-banner.html\">Full Width Banner</a></li>\r\n");
      out.write("                      <li><a href=\"shop-horizontal-filter.html\">Horizontal Filter<span\r\n");
      out.write("                              class=\"tip tip-hot\">Hot</span></a></li>\r\n");
      out.write("                      <li><a href=\"shop-off-canvas.html\">Off Canvas Sidebar<span\r\n");
      out.write("                              class=\"tip tip-new\">New</span></a></li>\r\n");
      out.write("                      <li><a href=\"shop-infinite-scroll.html\">Infinite Ajax Scroll</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li><a href=\"shop-right-sidebar.html\">Right Sidebar</a></li>\r\n");
      out.write("                      <li><a href=\"shop-both-sidebar.html\">Both Sidebar</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <h4 class=\"menu-title\">Shop Layouts</h4>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li><a href=\"shop-grid-3cols.html\">3 Columns Mode</a></li>\r\n");
      out.write("                      <li><a href=\"shop-grid-4cols.html\">4 Columns Mode</a></li>\r\n");
      out.write("                      <li><a href=\"shop-grid-5cols.html\">5 Columns Mode</a></li>\r\n");
      out.write("                      <li><a href=\"shop-grid-6cols.html\">6 Columns Mode</a></li>\r\n");
      out.write("                      <li><a href=\"shop-grid-7cols.html\">7 Columns Mode</a></li>\r\n");
      out.write("                      <li><a href=\"shop-grid-8cols.html\">8 Columns Mode</a></li>\r\n");
      out.write("                      <li><a href=\"shop-list.html\">List Mode</a></li>\r\n");
      out.write("                      <li><a href=\"shop-list-sidebar.html\">List Mode With Sidebar</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <h4 class=\"menu-title\">Product Pages</h4>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li><a href=\"product-variable.html\">Variable Product</a></li>\r\n");
      out.write("                      <li><a href=\"product-featured.html\">Featured &amp; Sale</a></li>\r\n");
      out.write("                      <li><a href=\"product-accordion.html\">Data In Accordion</a></li>\r\n");
      out.write("                      <li><a href=\"product-section.html\">Data In Sections</a></li>\r\n");
      out.write("                      <li><a href=\"product-swatch.html\">Image Swatch</a></li>\r\n");
      out.write("                      <li><a href=\"product-extended.html\">Extended Info</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li><a href=\"product-without-sidebar.html\">Without Sidebar</a></li>\r\n");
      out.write("                      <li><a href=\"product-video.html\">360<sup>o</sup> &amp; Video<span\r\n");
      out.write("                              class=\"tip tip-new\">New</span></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <h4 class=\"menu-title\">Product Layouts</h4>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li><a href=\"product-default.html\">Default<span\r\n");
      out.write("                              class=\"tip tip-hot\">Hot</span></a></li>\r\n");
      out.write("                      <li><a href=\"product-vertical.html\">Vertical Thumbs</a></li>\r\n");
      out.write("                      <li><a href=\"product-grid.html\">Grid Images</a></li>\r\n");
      out.write("                      <li><a href=\"product-masonry.html\">Masonry</a></li>\r\n");
      out.write("                      <li><a href=\"product-gallery.html\">Gallery</a></li>\r\n");
      out.write("                      <li><a href=\"product-sticky-info.html\">Sticky Info</a></li>\r\n");
      out.write("                      <li><a href=\"product-sticky-thumb.html\">Sticky Thumbs</a></li>\r\n");
      out.write("                      <li><a href=\"product-sticky-both.html\">Sticky Both</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- End of Megamenu -->\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"vendor-dokan-store.html\">Vendor</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"vendor-dokan-store-list.html\">Store Listing</a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li><a href=\"vendor-dokan-store-list.html\">Store listing 1</a></li>\r\n");
      out.write("                      <li><a href=\"vendor-wcfm-store-list.html\">Store listing 2</a></li>\r\n");
      out.write("                      <li><a href=\"vendor-wcmp-store-list.html\">Store listing 3</a></li>\r\n");
      out.write("                      <li><a href=\"vendor-wc-store-list.html\">Store listing 4</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"vendor-dokan-store.html\">Vendor Store</a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li><a href=\"vendor-dokan-store.html\">Vendor Store 1</a></li>\r\n");
      out.write("                      <li><a href=\"vendor-wcfm-store-product-grid.html\">Vendor Store 2</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li><a href=\"vendor-wcmp-store-product-grid.html\">Vendor Store 3</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                      <li><a href=\"vendor-wc-store-product-grid.html\">Vendor Store 4</a>\r\n");
      out.write("                      </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"blog.html\">Blog</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                  <li><a href=\"blog.html\">Classic</a></li>\r\n");
      out.write("                  <li><a href=\"blog-listing.html\">Listing</a></li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"blog-grid-3cols.html\">Grid</a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li><a href=\"blog-grid-2cols.html\">Grid 2 columns</a></li>\r\n");
      out.write("                      <li><a href=\"blog-grid-3cols.html\">Grid 3 columns</a></li>\r\n");
      out.write("                      <li><a href=\"blog-grid-4cols.html\">Grid 4 columns</a></li>\r\n");
      out.write("                      <li><a href=\"blog-grid-sidebar.html\">Grid sidebar</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"blog-masonry-3cols.html\">Masonry</a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li><a href=\"blog-masonry-2cols.html\">Masonry 2 columns</a></li>\r\n");
      out.write("                      <li><a href=\"blog-masonry-3cols.html\">Masonry 3 columns</a></li>\r\n");
      out.write("                      <li><a href=\"blog-masonry-4cols.html\">Masonry 4 columns</a></li>\r\n");
      out.write("                      <li><a href=\"blog-masonry-sidebar.html\">Masonry sidebar</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"blog-mask-grid.html\">Mask</a>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                      <li><a href=\"blog-mask-grid.html\">Blog mask grid</a></li>\r\n");
      out.write("                      <li><a href=\"blog-mask-masonry.html\">Blog mask masonry</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                    <a href=\"post-single.html\">Single Post</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"about-us.html\">Pages</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("\r\n");
      out.write("                  <li><a href=\"about-us.html\">About Us</a></li>\r\n");
      out.write("                  <li><a href=\"become-a-vendor.html\">Become A Vendor</a></li>\r\n");
      out.write("                  <li><a href=\"contact-us.html\">Contact Us</a></li>\r\n");
      out.write("                  <li><a href=\"faq.html\">FAQs</a></li>\r\n");
      out.write("                  <li><a href=\"error-404.html\">Error 404</a></li>\r\n");
      out.write("                  <li><a href=\"coming-soon.html\">Coming Soon</a></li>\r\n");
      out.write("                  <li><a href=\"wishlist.html\">Wishlist</a></li>\r\n");
      out.write("                  <li><a href=\"cart.html\">Cart</a></li>\r\n");
      out.write("                  <li><a href=\"checkout.html\">Checkout</a></li>\r\n");
      out.write("                  <li><a href=\"my-account.html\">My Account</a></li>\r\n");
      out.write("                  <li><a href=\"compare.html\">Compare</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li>\r\n");
      out.write("                <a href=\"elements.html\">Elements</a>\r\n");
      out.write("                <ul>\r\n");
      out.write("                  <li><a href=\"element-accordions.html\">Accordions</a></li>\r\n");
      out.write("                  <li><a href=\"element-alerts.html\">Alert &amp; Notification</a></li>\r\n");
      out.write("                  <li><a href=\"element-blog-posts.html\">Blog Posts</a></li>\r\n");
      out.write("                  <li><a href=\"element-buttons.html\">Buttons</a></li>\r\n");
      out.write("                  <li><a href=\"element-cta.html\">Call to Action</a></li>\r\n");
      out.write("                  <li><a href=\"element-icons.html\">Icons</a></li>\r\n");
      out.write("                  <li><a href=\"element-icon-boxes.html\">Icon Boxes</a></li>\r\n");
      out.write("                  <li><a href=\"element-instagrams.html\">Instagrams</a></li>\r\n");
      out.write("                  <li><a href=\"element-categories.html\">Product Category</a></li>\r\n");
      out.write("                  <li><a href=\"element-products.html\">Products</a></li>\r\n");
      out.write("                  <li><a href=\"element-tabs.html\">Tabs</a></li>\r\n");
      out.write("                  <li><a href=\"element-testimonials.html\">Testimonials</a></li>\r\n");
      out.write("                  <li><a href=\"element-titles.html\">Titles</a></li>\r\n");
      out.write("                  <li><a href=\"element-typography.html\">Typography</a></li>\r\n");
      out.write("\r\n");
      out.write("                  <li><a href=\"element-vendors.html\">Vendors</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"header-right\">\r\n");
      out.write("          <a href=\"#\" class=\"d-xl-show\"><i class=\"w-icon-map-marker mr-1\"></i>Track Order</a>\r\n");
      out.write("          <a href=\"#\"><i class=\"w-icon-sale\"></i>Daily Deals</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</header>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
