/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-25 14:04:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("file:/C:/Users/SACHINTHA/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1692466006702L));
    _jspx_dependants.put("file:/C:/Users/SACHINTHA/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244559614L));
    _jspx_dependants.put("jar:file:/C:/Users/SACHINTHA/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
    _jspx_dependants.put("jar:file:/C:/Users/SACHINTHA/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664433678000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/cart.jsp(3,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("other");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/cart.jsp(4,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("content");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(new jakarta.servlet.jsp.tagext.TagAdapter((jakarta.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/views/frontend/cart.jsp(36,28) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/frontend/cart.jsp(36,28) '${model}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${model}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/frontend/cart.jsp(36,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("cartItem");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                            <tr>\r\n");
            out.write("                                <td class=\"product-thumbnail\">\r\n");
            out.write("                                    <div class=\"p-relative\">\r\n");
            out.write("                                        <a href=\"product-default.html\">\r\n");
            out.write("                                            <figure>\r\n");
            out.write("                                                <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartItem.product.getThumbnail()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"product\"\r\n");
            out.write("                                                     width=\"300\" height=\"338\">\r\n");
            out.write("                                            </figure>\r\n");
            out.write("                                        </a>\r\n");
            out.write("                                        <button type=\"submit\" class=\"btn btn-close\"><i\r\n");
            out.write("                                                class=\"fas fa-times\"></i></button>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                </td>\r\n");
            out.write("                                <td class=\"product-name\">\r\n");
            out.write("                                    <a href=\"product-default.html\">\r\n");
            out.write("                                        ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartItem.product.getName()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("                                    </a>\r\n");
            out.write("                                </td>\r\n");
            out.write("                                <td class=\"product-price\"><span class=\"amount\">$");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cartItem.product.getPrice()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span></td>\r\n");
            out.write("                                <td class=\"product-quantity\">\r\n");
            out.write("                                    <div class=\"input-group\">\r\n");
            out.write("                                        <input class=\"quantity form-control\" type=\"number\" min=\"1\" max=\"100000\">\r\n");
            out.write("                                        <button class=\"quantity-plus w-icon-plus\"></button>\r\n");
            out.write("                                        <button class=\"quantity-minus w-icon-minus\"></button>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                </td>\r\n");
            out.write("                                <td class=\"product-subtotal\">\r\n");
            out.write("                                    <span class=\"amount\">$40.00</span>\r\n");
            out.write("                                </td>\r\n");
            out.write("                            </tr>\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new jakarta.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\r');
      out.write('\n');
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Start of Main -->\r\n");
      out.write("    <main class=\"main cart\">\r\n");
      out.write("        <!-- Start of Breadcrumb -->\r\n");
      out.write("        <nav class=\"breadcrumb-nav\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <ul class=\"breadcrumb shop-breadcrumb bb-no\">\r\n");
      out.write("                    <li class=\"active\"><a href=\"cart.html\">Shopping Cart</a></li>\r\n");
      out.write("                    <li><a href=\"checkout.html\">Checkout</a></li>\r\n");
      out.write("                    <li><a href=\"order.html\">Order Complete</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- End of Breadcrumb -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Start of PageContent -->\r\n");
      out.write("        <div class=\"page-content\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row gutter-lg mb-10\">\r\n");
      out.write("                    <div class=\"col-lg-8 pr-lg-4 mb-6\">\r\n");
      out.write("                        <table class=\"shop-table cart-table\">\r\n");
      out.write("                            <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th class=\"product-name\"><span>Product</span></th>\r\n");
      out.write("                                <th></th>\r\n");
      out.write("                                <th class=\"product-price\"><span>Price</span></th>\r\n");
      out.write("                                <th class=\"product-quantity\"><span>Quantity</span></th>\r\n");
      out.write("                                <th class=\"product-subtotal\"><span>Subtotal</span></th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                            </thead>\r\n");
      out.write("                            <tbody>\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </tbody>\r\n");
      out.write("                        </table>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"cart-action mb-6\">\r\n");
      out.write("                            <a href=\"#\" class=\"btn btn-dark btn-rounded btn-icon-left btn-shopping mr-auto\"><i class=\"w-icon-long-arrow-left\"></i>Continue Shopping</a>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-rounded btn-default btn-clear\" name=\"clear_cart\" value=\"Clear Cart\">Clear Cart</button>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-rounded btn-update disabled\" name=\"update_cart\" value=\"Update Cart\">Update Cart</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <form class=\"coupon\">\r\n");
      out.write("                            <h5 class=\"title coupon-title font-weight-bold text-uppercase\">Coupon Discount</h5>\r\n");
      out.write("                            <input type=\"text\" class=\"form-control mb-4\" placeholder=\"Enter coupon code here...\" required />\r\n");
      out.write("                            <button class=\"btn btn-dark btn-outline btn-rounded\">Apply Coupon</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-lg-4 sticky-sidebar-wrapper\">\r\n");
      out.write("                        <div class=\"sticky-sidebar\">\r\n");
      out.write("                            <div class=\"cart-summary mb-4\">\r\n");
      out.write("                                <h3 class=\"cart-title text-uppercase\">Cart Totals</h3>\r\n");
      out.write("                                <div class=\"cart-subtotal d-flex align-items-center justify-content-between\">\r\n");
      out.write("                                    <label class=\"ls-25\">Subtotal</label>\r\n");
      out.write("                                    <span>$100.00</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <hr class=\"divider\">\r\n");
      out.write("\r\n");
      out.write("                                <ul class=\"shipping-methods mb-2\">\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <label\r\n");
      out.write("                                                class=\"shipping-title text-dark font-weight-bold\">Shipping</label>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"custom-radio\">\r\n");
      out.write("                                            <input type=\"radio\" id=\"free-shipping\" class=\"custom-control-input\"\r\n");
      out.write("                                                   name=\"shipping\">\r\n");
      out.write("                                            <label for=\"free-shipping\"\r\n");
      out.write("                                                   class=\"custom-control-label color-dark\">Free\r\n");
      out.write("                                                Shipping</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"custom-radio\">\r\n");
      out.write("                                            <input type=\"radio\" id=\"local-pickup\" class=\"custom-control-input\"\r\n");
      out.write("                                                   name=\"shipping\">\r\n");
      out.write("                                            <label for=\"local-pickup\"\r\n");
      out.write("                                                   class=\"custom-control-label color-dark\">Local\r\n");
      out.write("                                                Pickup</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li>\r\n");
      out.write("                                        <div class=\"custom-radio\">\r\n");
      out.write("                                            <input type=\"radio\" id=\"flat-rate\" class=\"custom-control-input\"\r\n");
      out.write("                                                   name=\"shipping\">\r\n");
      out.write("                                            <label for=\"flat-rate\" class=\"custom-control-label color-dark\">Flat\r\n");
      out.write("                                                rate:\r\n");
      out.write("                                                $5.00</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"shipping-calculator\">\r\n");
      out.write("                                    <p class=\"shipping-destination lh-1\">Shipping to <strong>CA</strong>.</p>\r\n");
      out.write("\r\n");
      out.write("                                    <form class=\"shipping-calculator-form\">\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <div class=\"select-box\">\r\n");
      out.write("                                                <select name=\"country\" class=\"form-control form-control-md\">\r\n");
      out.write("                                                    <option value=\"default\" selected=\"selected\">United States\r\n");
      out.write("                                                        (US)\r\n");
      out.write("                                                    </option>\r\n");
      out.write("                                                    <option value=\"us\">United States</option>\r\n");
      out.write("                                                    <option value=\"uk\">United Kingdom</option>\r\n");
      out.write("                                                    <option value=\"fr\">France</option>\r\n");
      out.write("                                                    <option value=\"aus\">Australia</option>\r\n");
      out.write("                                                </select>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <div class=\"select-box\">\r\n");
      out.write("                                                <select name=\"state\" class=\"form-control form-control-md\">\r\n");
      out.write("                                                    <option value=\"default\" selected=\"selected\">California\r\n");
      out.write("                                                    </option>\r\n");
      out.write("                                                    <option value=\"ohaio\">Ohaio</option>\r\n");
      out.write("                                                </select>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input class=\"form-control form-control-md\" type=\"text\"\r\n");
      out.write("                                                   name=\"town-city\" placeholder=\"Town / City\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"form-group\">\r\n");
      out.write("                                            <input class=\"form-control form-control-md\" type=\"text\"\r\n");
      out.write("                                                   name=\"zipcode\" placeholder=\"ZIP\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <button type=\"submit\" class=\"btn btn-dark btn-outline btn-rounded\">Update\r\n");
      out.write("                                            Totals</button>\r\n");
      out.write("                                    </form>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <hr class=\"divider mb-6\">\r\n");
      out.write("                                <div class=\"order-total d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                    <label>Total</label>\r\n");
      out.write("                                    <span class=\"ls-50\">$100.00</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"#\"\r\n");
      out.write("                                   class=\"btn btn-block btn-dark btn-icon-right btn-rounded  btn-checkout\">\r\n");
      out.write("                                    Proceed to checkout<i class=\"w-icon-long-arrow-right\"></i></a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of PageContent -->\r\n");
      out.write("    </main>\r\n");
      out.write("    <!-- End of Main -->\r\n");
      out.write("\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
