/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-26 07:58:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/coman/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664433678000L));
    _jspx_dependants.put("jar:file:/C:/Users/coman/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
    _jspx_dependants.put("file:/C:/Users/coman/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1695710950679L));
    _jspx_dependants.put("file:/C:/Users/coman/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1695710965715L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/home.jsp(3,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/home.jsp(5,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("content");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(new jakarta.servlet.jsp.tagext.TagAdapter((jakarta.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/views/frontend/home.jsp(233,28) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/frontend/home.jsp(233,28) '${model.categories}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${model.categories}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/frontend/home.jsp(233,28) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("category");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                <div class=\"swiper-slide category category-ellipse\">\r\n");
            out.write("                                    <figure class=\"category-media\">\r\n");
            out.write("                                        <a href=\"shop-banner-sidebar.html\">\r\n");
            out.write("                                            <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.getThumbnail()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"Categroy\" width=\"190\"\r\n");
            out.write("                                                 height=\"190\" style=\"background-color: #5C92C0;\"/>\r\n");
            out.write("                                        </a>\r\n");
            out.write("                                    </figure>\r\n");
            out.write("                                    <div class=\"category-content\">\r\n");
            out.write("                                        <h4 class=\"category-name\">\r\n");
            out.write('\r');
            out.write('\n');
            out.write("\r\n");
            out.write("                                            <a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("category?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${category.getName()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("                                        </h4>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                </div>\r\n");
            out.write("                            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new jakarta.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(new jakarta.servlet.jsp.tagext.TagAdapter((jakarta.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/views/frontend/home.jsp(271,32) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/frontend/home.jsp(271,32) '${model.products}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${model.products}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/frontend/home.jsp(271,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("product");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                    <div class=\"swiper-slide product-wrap mt-3\">\r\n");
            out.write("                                        <div class=\"product product-simple text-center\">\r\n");
            out.write("                                            <figure class=\"product-media\">\r\n");
            out.write("                                                <a href=\"product-default.html\">\r\n");
            out.write("                                                    <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getThumbnail()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"Product\"\r\n");
            out.write("                                                         width=\"330\" height=\"338\"/>\r\n");
            out.write("                                                    <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getThumbnail()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" alt=\"Product\"\r\n");
            out.write("                                                         width=\"330\" height=\"338\"/>\r\n");
            out.write("                                                </a>\r\n");
            out.write("                                                <div class=\"product-action-vertical\">\r\n");
            out.write("                                                    <a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("wishlist/add?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"btn-product-icon w-icon-heart\"\r\n");
            out.write("                                                       title=\"Add to wishlist\"></a>\r\n");
            out.write("                                                </div>\r\n");
            out.write("                                                <div class=\"product-action\">\r\n");
            out.write("                                                    <a href=\"#\" class=\"btn-product btn-quickview\" title=\"Quick View\">Quick\r\n");
            out.write("                                                        View</a>\r\n");
            out.write("                                                </div>\r\n");
            out.write("                                            </figure>\r\n");
            out.write("                                            <div class=\"product-details\">\r\n");
            out.write("                                                <h4 class=\"product-name\"><a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("product-view?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getName()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a>\r\n");
            out.write("                                                </h4>\r\n");
            out.write("                                                <div class=\"ratings-container\">\r\n");
            out.write("                                                    <div class=\"ratings-full\">\r\n");
            out.write("                                                        <span class=\"ratings\" style=\"width: 100%;\"></span>\r\n");
            out.write("                                                        <span class=\"tooltiptext tooltip-top\"></span>\r\n");
            out.write("                                                    </div>\r\n");
            out.write("                                                    <a href=\"product-default.html\" class=\"rating-reviews\">(3\r\n");
            out.write("                                                        reviews)</a>\r\n");
            out.write("                                                </div>\r\n");
            out.write("                                                <div class=\"product-pa-wrapper\">\r\n");
            out.write("                                                    <div class=\"product-price\">\r\n");
            out.write("                                                        <ins class=\"new-price\">$");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.getPrice()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("0</ins>\r\n");
            out.write("                                                    </div>\r\n");
            out.write("                                                    <div class=\"product-action\">\r\n");
            out.write("                                                        <a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("add-to-cart?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("                                                           class=\"btn btn-icon-right btn-link\">Add\r\n");
            out.write("                                                            To Cart</a>\r\n");
            out.write("                                                    </div>\r\n");
            out.write("                                                </div>\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new jakarta.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        <!-- Start of Main -->\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"mb-4\">\r\n");
      out.write("                    <div class=\"swiper-container swiper-theme nav-inner swiper-nav-md animation-slider\"\r\n");
      out.write("                         data-swiper-options=\"{\r\n");
      out.write("                        'autoplay': {\r\n");
      out.write("                            'delay': 8000,\r\n");
      out.write("                            'disableOnInteraction': false\r\n");
      out.write("                        }\r\n");
      out.write("                    }\">\r\n");
      out.write("                        <div class=\"swiper-wrapper row cols-1 gutter-no\">\r\n");
      out.write("                            <div class=\"swiper-slide banner banner-fixed intro-slide intro-slide1 br-sm\" style=\"background-image: url(assets/images/demos/demo3/slides/slide-1.jpg);\r\n");
      out.write("                            background-color: #262729;\">\r\n");
      out.write("                                <div class=\"banner-content y-50 x-50 w-100 text-center\">\r\n");
      out.write("                                    <h5 class=\"banner-subtitle text-primary font-weight-normal text-capitalize font-secondary ls-25 slide-animate\"\r\n");
      out.write("                                        data-animation-options=\"{'name': 'fadeInDownShorter', 'duration': '.8s'}\">Mega\r\n");
      out.write("                                        Sale\r\n");
      out.write("                                    </h5>\r\n");
      out.write("                                    <h3 class=\"banner-title text-white text-capitalize ls-25 lh-1 slide-animate\"\r\n");
      out.write("                                        data-animation-options=\"{'name': 'fadeInRightShorter', 'duration': '.5s', 'delay': '.5s'}\">\r\n");
      out.write("                                        2021 Men's Lifestyle</h3>\r\n");
      out.write("                                    <p class=\"ls-25 slide-animate\" data-animation-options=\"{\r\n");
      out.write("                                        'name': 'fadeInLeftShorter', 'duration': '.5s', 'delay': '.5s'\r\n");
      out.write("                                    }\">Get Free Shipping on all orders over $99.00</p>\r\n");
      out.write("                                    <a href=\"shop-banner-sidebar.html\"\r\n");
      out.write("                                       class=\"btn btn-white btn-outline btn-rounded btn-icon-right slide-animate\"\r\n");
      out.write("                                       data-animation-options=\"{'name': 'fadeInUpShorter', 'duration': '.5s', 'delay': '.5s'}\">\r\n");
      out.write("                                        Shop Now<i class=\"w-icon-long-arrow-right\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- End Of Intro Slide 1 -->\r\n");
      out.write("                            <div class=\"swiper-slide banner banner-fixed intro-slide intro-slide2  br-sm\" style=\"background-image: url(assets/images/demos/demo3/slides/slide-2.jpg);\r\n");
      out.write("                                background-color: #DCE0DF;\">\r\n");
      out.write("                                <div class=\"banner-content y-50\">\r\n");
      out.write("                                    <h5 class=\"banner-subtitle text-primary font-secondary font-weight-normal text-capitalize mb-0 lh-1 ls-25 slide-animate\"\r\n");
      out.write("                                        data-animation-options=\"{'name': 'fadeInDownShorter', 'duration': '.8s'}\">Best\r\n");
      out.write("                                        Seller</h5>\r\n");
      out.write("                                    <h3 class=\"banner-title text-capitalize lh-.8 slide-animate\"\r\n");
      out.write("                                        data-animation-options=\"{'name': 'fadeInDownShorter', 'duration': '.8s', 'delay': '.4s'}\">\r\n");
      out.write("                                        Kitchen Electronic</h3>\r\n");
      out.write("                                    <p class=\"text-default font-weight-normal ls-25 slide-animate\"\r\n");
      out.write("                                       data-animation-options=\"{\r\n");
      out.write("                                        'name': 'fadeInDownShorter', 'duration': '.8s', 'delay': '.6s'\r\n");
      out.write("                                    }\">Get Free Shipping on all orders over <strong class=\"text-primary\">$99.00</strong>\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                    <a href=\"shop-banner-sidebar.html\"\r\n");
      out.write("                                       class=\"btn btn-white btn-rounded btn-icon-right slide-animate\"\r\n");
      out.write("                                       data-animation-options=\"{'name': 'fadeInDownShorter', 'duration': '.8s', 'delay': '.8s'}\">Shop\r\n");
      out.write("                                        Now<i class=\"w-icon-long-arrow-right\"></i></a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <!-- End of Intro Slide 3 -->\r\n");
      out.write("                            <div class=\"swiper-slide banner banner-fixed intro-slide intro-slide3 br-sm\" style=\"background-image: url(assets/images/demos/demo3/slides/slide-3.jpg);\r\n");
      out.write("                                background-color: #696A6E;\">\r\n");
      out.write("                                <div class=\"banner-content y-50 text-right\">\r\n");
      out.write("                                    <div class=\"slide-animate\" data-animation-options=\"{\r\n");
      out.write("                                        'name': 'fadeInUpShorter', 'duration': '.7s'\r\n");
      out.write("                                    }\">\r\n");
      out.write("                                        <h5\r\n");
      out.write("                                                class=\"banner-subtitle text-primary font-secondary font-weight-normal ls-25 mb-0 lh-1\">\r\n");
      out.write("                                            New Arrivals</h5>\r\n");
      out.write("                                        <h3 class=\"banner-title text-white text-capitalize lh-1\">Sports Sneakers</h3>\r\n");
      out.write("                                        <p class=\"text-white ls-25\">Get Free Shipping on all orders over\r\n");
      out.write("                                            <strong>$99.00</strong></p>\r\n");
      out.write("                                        <a href=\"shop-banner-sidebar.html\"\r\n");
      out.write("                                           class=\"btn btn-white btn-outline btn-rounded btn-icon-right\">\r\n");
      out.write("                                            Shop Now<i class=\"w-icon-long-arrow-right\"></i></a>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <button class=\"swiper-button-next\"></button>\r\n");
      out.write("                        <button class=\"swiper-button-prev\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End of Intro Wrapper -->\r\n");
      out.write("                <div class=\"swiper-container swiper-theme intro-banner appear-animate\" data-swiper-options=\"{\r\n");
      out.write("                    'spaceBetween': 20,\r\n");
      out.write("                    'slidesPerView': 1,\r\n");
      out.write("                    'breakpoints': {\r\n");
      out.write("                        '576': {\r\n");
      out.write("                            'slidesPerView': 2,\r\n");
      out.write("                            'spaceBetween': 15\r\n");
      out.write("                        },\r\n");
      out.write("                        '992': {\r\n");
      out.write("                            'slidesPerView': 3\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\">\r\n");
      out.write("                    <div class=\"swiper-wrapper row cols-lg-3 cols-sm-2 cols-1\">\r\n");
      out.write("                        <div class=\"swiper-slide\">\r\n");
      out.write("                            <figure class=\"banner banner-fixed br-sm\">\r\n");
      out.write("                                <img src=\"assets/images/demos/demo3/categories/1.jpg\" alt=\"Category Banner\" width=\"400\"\r\n");
      out.write("                                     height=\"200\" style=\"background-color: #3C3C3C;\"/>\r\n");
      out.write("                                <div class=\"banner-content y-50\">\r\n");
      out.write("                                    <h5 class=\"banner-subtitle text-primary text-uppercase font-weight-bold ls-25\">Top\r\n");
      out.write("                                        Products\r\n");
      out.write("                                    </h5>\r\n");
      out.write("                                    <h3 class=\"banner-title text-white font-weight-bold\">Tranding NIKE<br>Sneaker</h3>\r\n");
      out.write("                                    <a href=\"shop-banner-sidebar.html\"\r\n");
      out.write("                                       class=\"btn btn-white btn-link btn-underline btn-icon-right\">\r\n");
      out.write("                                        Shop Now<i class=\"w-icon-long-arrow-right\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </figure>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"swiper-slide\">\r\n");
      out.write("                            <figure class=\"banner banner-fixed br-sm\">\r\n");
      out.write("                                <img src=\"assets/images/demos/demo3/categories/2.jpg\" alt=\"Category Banner\" width=\"400\"\r\n");
      out.write("                                     height=\"200\" style=\"background-color: #E1E1E1;\"/>\r\n");
      out.write("                                <div class=\"banner-content y-50\">\r\n");
      out.write("                                    <h5 class=\"banner-subtitle text-primary text-uppercase font-weight-bold ls-25\">New\r\n");
      out.write("                                        Arrivals\r\n");
      out.write("                                    </h5>\r\n");
      out.write("                                    <h3 class=\"banner-title ls-25\">Vegan Friendly<br>Makeup</h3>\r\n");
      out.write("                                    <a href=\"shop-banner-sidebar.html\"\r\n");
      out.write("                                       class=\"btn btn-dark btn-link btn-underline btn-icon-right\">\r\n");
      out.write("                                        Shop Now<i class=\"w-icon-long-arrow-right\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </figure>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"swiper-slide\">\r\n");
      out.write("                            <figure class=\"banner banner-fixed br-sm\">\r\n");
      out.write("                                <img src=\"assets/images/demos/demo3/categories/3.jpg\" alt=\"Category Banner\" width=\"400\"\r\n");
      out.write("                                     height=\"200\" style=\"background-color: #57585D;\"/>\r\n");
      out.write("                                <div class=\"banner-content y-50\">\r\n");
      out.write("                                    <h5 class=\"banner-subtitle text-primary text-uppercase font-weight-bold ls-25\">Best\r\n");
      out.write("                                        Seller\r\n");
      out.write("                                    </h5>\r\n");
      out.write("                                    <h3 class=\"banner-title text-white font-weight-bold ls-15\">Fashion Apple<br>Accessories\r\n");
      out.write("                                    </h3>\r\n");
      out.write("                                    <a href=\"shop-banner-sidebar.html\"\r\n");
      out.write("                                       class=\"btn btn-white btn-link btn-underline btn-icon-right\">\r\n");
      out.write("                                        Shop Now<i class=\"w-icon-long-arrow-right\"></i>\r\n");
      out.write("                                    </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </figure>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"swiper-pagination\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"swiper-container swiper-theme icon-box-wrapper appear-animate br-sm mt-6 mb-10\"\r\n");
      out.write("                     data-swiper-options=\"{\r\n");
      out.write("                    'slidesPerView': 1,\r\n");
      out.write("                    'breakpoints': {\r\n");
      out.write("                        '576': {\r\n");
      out.write("                            'slidesPerView': 2\r\n");
      out.write("                        },\r\n");
      out.write("                        '768': {\r\n");
      out.write("                            'slidesPerView': 3\r\n");
      out.write("                        },\r\n");
      out.write("                        '992': {\r\n");
      out.write("                            'slidesPerView': 3\r\n");
      out.write("                        },\r\n");
      out.write("                        '1200': {\r\n");
      out.write("                            'slidesPerView': 4\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\">\r\n");
      out.write("                    <div class=\"swiper-wrapper row cols-md-4 cols-sm-3 cols-1\">\r\n");
      out.write("                        <div class=\"swiper-slide icon-box icon-box-side text-dark\">\r\n");
      out.write("                            <span class=\"icon-box-icon icon-shipping\">\r\n");
      out.write("                                <i class=\"w-icon-truck\"></i>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <div class=\"icon-box-content\">\r\n");
      out.write("                                <h4 class=\"icon-box-title mb-1 ls-normal\">Free Shipping & Returns</h4>\r\n");
      out.write("                                <p class=\"text-default\">For all orders over $99</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"swiper-slide icon-box icon-box-side text-dark\">\r\n");
      out.write("                            <span class=\"icon-box-icon icon-payment\">\r\n");
      out.write("                                <i class=\"w-icon-bag\"></i>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <div class=\"icon-box-content\">\r\n");
      out.write("                                <h4 class=\"icon-box-title mb-1 ls-normal\">Secure Payment</h4>\r\n");
      out.write("                                <p class=\"text-default\">We ensure secure payment</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"swiper-slide icon-box icon-box-side text-dark icon-box-money\">\r\n");
      out.write("                            <span class=\"icon-box-icon icon-money\">\r\n");
      out.write("                                <i class=\"w-icon-money\"></i>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <div class=\"icon-box-content\">\r\n");
      out.write("                                <h4 class=\"icon-box-title mb-1 ls-normal\">Money Back Guarantee</h4>\r\n");
      out.write("                                <p class=\"text-default\">Any back within 30 days</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"swiper-slide icon-box icon-box-side text-dark icon-box-chat\">\r\n");
      out.write("                            <span class=\"icon-box-icon icon-chat\">\r\n");
      out.write("                                <i class=\"w-icon-chat\"></i>\r\n");
      out.write("                            </span>\r\n");
      out.write("                            <div class=\"icon-box-content\">\r\n");
      out.write("                                <h4 class=\"icon-box-title mb-1 ls-normal\">Customer Support</h4>\r\n");
      out.write("                                <p class=\"text-default\">Call or email us 24/7</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- End of Iocn Box Wrapper -->\r\n");
      out.write("\r\n");
      out.write("                <h2 class=\"title text-left pt-1 mb-5 appear-animate\">Categories</h2>\r\n");
      out.write("                <div class=\"swiper\">\r\n");
      out.write("                    <div class=\"swiper-container category-wrapper swiper-theme appear-animate\" data-swiper-options=\"{\r\n");
      out.write("                        'spaceBetween': 20,\r\n");
      out.write("                        'slidesPerView': 2,\r\n");
      out.write("                        'breakpoints': {\r\n");
      out.write("                            '576': {\r\n");
      out.write("                                'slidesPerView': 3\r\n");
      out.write("                            },\r\n");
      out.write("                            '768': {\r\n");
      out.write("                                'slidesPerView': 3\r\n");
      out.write("                            },\r\n");
      out.write("                            '992': {\r\n");
      out.write("                                'slidesPerView': 3\r\n");
      out.write("                            },\r\n");
      out.write("                            '1200': {\r\n");
      out.write("                                'slidesPerView': 3\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\">\r\n");
      out.write("                        <div class=\"swiper-wrapper row cols-xl-6 cols-lg-5 cols-md-4 cols-sm-3 cols-2\">\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"swiper-pagination\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <h2 class=\"title text-left appear-animate mb-5\">Clothing &amp; Appreal</h2>\r\n");
      out.write("                <div class=\"row banner-product-wrapper appear-animate mb-10\">\r\n");
      out.write("                    <div class=\"col-lg-12 mb-4 mb-lg-0\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"swiper-theme mt-4\" data-swiper-options=\"{\r\n");
      out.write("                            'spaceBetween': 20,\r\n");
      out.write("                            'slidesPerView': 1,\r\n");
      out.write("                            'breakpoints': {,\r\n");
      out.write("                                '1200': {\r\n");
      out.write("                                    'slidesPerView': 4\r\n");
      out.write("                                }\r\n");
      out.write("                            }\r\n");
      out.write("                        }\">\r\n");
      out.write("                            <div class=\"swiper-wrapper row cols-md-4 cols-sm-3 cols-2\">\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("                                <!-- End of Product Wrap -->\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- End of Container -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of Main -->\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
