/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-26 03:31:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class wishlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("file:/C:/Users/SACHINTHA/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1692466006702L));
    _jspx_dependants.put("file:/C:/Users/SACHINTHA/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244559614L));
    _jspx_dependants.put("jar:file:/C:/Users/SACHINTHA/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
    _jspx_dependants.put("jar:file:/C:/Users/SACHINTHA/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664433678000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/wishlist.jsp(4,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("other");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/wishlist.jsp(6,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("content");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("    <!-- Start of Main -->\r\n");
      out.write("    <main class=\"main wishlist-page\">\r\n");
      out.write("        <!-- Start of Page Header -->\r\n");
      out.write("        <div class=\"page-header\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <h1 class=\"page-title mb-0\">Wishlist</h1>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of Page Header -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Start of Breadcrumb -->\r\n");
      out.write("        <nav class=\"breadcrumb-nav mb-10\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <ul class=\"breadcrumb\">\r\n");
      out.write("                    <li><a href=\"demo1.html\">Home</a></li>\r\n");
      out.write("                    <li>Wishlist</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <!-- End of Breadcrumb -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Start of PageContent -->\r\n");
      out.write("        <div class=\"page-content\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <h3 class=\"wishlist-title\">My wishlist</h3>\r\n");
      out.write("                <table class=\"shop-table wishlist-table\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <th class=\"product-name\"><span>Product</span></th>\r\n");
      out.write("                        <th></th>\r\n");
      out.write("                        <th class=\"product-price\"><span>Price</span></th>\r\n");
      out.write("                        <th class=\"product-stock-status\"><span>Stock Status</span></th>\r\n");
      out.write("                        <th class=\"wishlist-action\">Actions</th>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"product-thumbnail\">\r\n");
      out.write("                            <div class=\"p-relative\">\r\n");
      out.write("                                <a href=\"product-default.html\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"assets/images/shop/7-1.jpg\" alt=\"product\" width=\"300\"\r\n");
      out.write("                                             height=\"338\">\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-close\"><i\r\n");
      out.write("                                        class=\"fas fa-times\"></i></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"product-name\">\r\n");
      out.write("                            <a href=\"product-default.html\">\r\n");
      out.write("                                Blue Sky Trunk\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"product-price\">\r\n");
      out.write("                            <ins class=\"new-price\">$85.00</ins>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"product-stock-status\">\r\n");
      out.write("                            <span class=\"wishlist-in-stock\">In Stock</span>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"wishlist-action\">\r\n");
      out.write("                            <div class=\"d-lg-flex\">\r\n");
      out.write("                                <a href=\"#\"\r\n");
      out.write("                                   class=\"btn btn-quickview btn-outline btn-default btn-rounded btn-sm mb-2 mb-lg-0\">Quick\r\n");
      out.write("                                    View</a>\r\n");
      out.write("                                <a href=\"#\" class=\"btn btn-dark btn-rounded btn-sm ml-lg-2 btn-cart\">Add to\r\n");
      out.write("                                    cart</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"product-thumbnail\">\r\n");
      out.write("                            <div class=\"p-relative\">\r\n");
      out.write("                                <a href=\"product-default.html\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"assets/images/shop/19-1.jpg\" alt=\"product\" width=\"300\"\r\n");
      out.write("                                             height=\"338\">\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-close\"><i\r\n");
      out.write("                                        class=\"fas fa-times\"></i></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"product-name\">\r\n");
      out.write("                            <a href=\"product-default.html\">\r\n");
      out.write("                                Handmade Ring\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"product-price\"><ins class=\"new-price\">$5.00</ins></td>\r\n");
      out.write("                        <td class=\"product-stock-status\">\r\n");
      out.write("                            <span class=\"wishlist-in-stock\">In Stock</span>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"wishlist-action\">\r\n");
      out.write("                            <div class=\"d-lg-flex\">\r\n");
      out.write("                                <a href=\"#\"\r\n");
      out.write("                                   class=\"btn btn-quickview btn-outline btn-default btn-rounded btn-sm mb-2 mb-lg-0\">Quick\r\n");
      out.write("                                    View</a>\r\n");
      out.write("                                <a href=\"#\" class=\"btn btn-dark btn-rounded btn-sm ml-lg-2 btn-cart\">Add to\r\n");
      out.write("                                    cart</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr>\r\n");
      out.write("                        <td class=\"product-thumbnail\">\r\n");
      out.write("                            <div class=\"p-relative\">\r\n");
      out.write("                                <a href=\"product-default.html\">\r\n");
      out.write("                                    <figure>\r\n");
      out.write("                                        <img src=\"assets/images/shop/20.jpg\" alt=\"product\" width=\"300\"\r\n");
      out.write("                                             height=\"338\">\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <button type=\"submit\" class=\"btn btn-close\"><i\r\n");
      out.write("                                        class=\"fas fa-times\"></i></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"product-name\">\r\n");
      out.write("                            <a href=\"product-default.html\">\r\n");
      out.write("                                Pencil Case\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"product-price\"><ins class=\"new-price\">$54.00</ins></td>\r\n");
      out.write("                        <td class=\"product-stock-status\">\r\n");
      out.write("                            <span class=\"wishlist-in-stock\">In Stock</span>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td class=\"wishlist-action\">\r\n");
      out.write("                            <div class=\"d-lg-flex\">\r\n");
      out.write("                                <a href=\"#\"\r\n");
      out.write("                                   class=\"btn btn-quickview btn-outline btn-default btn-rounded btn-sm mb-2 mb-lg-0\">Quick\r\n");
      out.write("                                    View</a>\r\n");
      out.write("                                <a href=\"#\" class=\"btn btn-dark btn-rounded btn-sm ml-lg-2 btn-cart\">Add to\r\n");
      out.write("                                    cart</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("                <div class=\"social-links\">\r\n");
      out.write("                    <label>Share On:</label>\r\n");
      out.write("                    <div class=\"social-icons social-no-color border-thin\">\r\n");
      out.write("                        <a href=\"#\" class=\"social-icon social-facebook w-icon-facebook\"></a>\r\n");
      out.write("                        <a href=\"#\" class=\"social-icon social-twitter w-icon-twitter\"></a>\r\n");
      out.write("                        <a href=\"#\" class=\"social-icon social-pinterest w-icon-pinterest\"></a>\r\n");
      out.write("                        <a href=\"#\" class=\"social-icon social-email far fa-envelope\"></a>\r\n");
      out.write("                        <a href=\"#\" class=\"social-icon social-whatsapp fab fa-whatsapp\"></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End of PageContent -->\r\n");
      out.write("    </main>\r\n");
      out.write("    <!-- End of Main -->\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
