/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-25 14:35:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.auth;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("    <title>Luminary Clothing</title>\r\n");
      out.write("\r\n");
      out.write("    <meta name=\"keywords\" content=\"Marketplace ecommerce responsive HTML5 Template\" />\r\n");
      out.write("    <meta name=\"description\" content=\"Wolmart is powerful marketplace &amp; ecommerce responsive Html5 Template.\">\r\n");
      out.write("    <meta name=\"author\" content=\"D-THEMES\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" href=\"assets/images/icons/luminary_logo.png\">\r\n");
      out.write("\r\n");
      out.write("    <!-- WebFont.js -->\r\n");
      out.write("    <script>\r\n");
      out.write("        WebFontConfig = {\r\n");
      out.write("            google: { families: ['Poppins:400,500,600,700'] }\r\n");
      out.write("        };\r\n");
      out.write("        ( function ( d ) {\r\n");
      out.write("            var wf = d.createElement( 'script' ), s = d.scripts[0];\r\n");
      out.write("            wf.src = 'assets/js/webfont.js';\r\n");
      out.write("            wf.async = true;\r\n");
      out.write("            s.parentNode.insertBefore( wf, s );\r\n");
      out.write("        } )( document );\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"preload\" href=\"assets/vendor/fontawesome-free/webfonts/fa-regular-400.woff2\" as=\"font\" type=\"font/woff2\"\r\n");
      out.write("          crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"preload\" href=\"assets/vendor/fontawesome-free/webfonts/fa-solid-900.woff2\" as=\"font\" type=\"font/woff2\"\r\n");
      out.write("          crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"preload\" href=\"assets/vendor/fontawesome-free/webfonts/fa-brands-400.woff2\" as=\"font\" type=\"font/woff2\"\r\n");
      out.write("          crossorigin=\"anonymous\">\r\n");
      out.write("    <link rel=\"preload\" href=\"assets/fonts/wolmart.woff?png09e\" as=\"font\" type=\"font/woff\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Vendor CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendor/fontawesome-free/css/all.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"assets/vendor/swiper/swiper-bundle.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Plugin CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/vendor/magnific-popup/magnific-popup.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Default CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/css/style.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"page-wrapper\">\r\n");
      out.write("    <!-- Start of Header -->\r\n");
      out.write("\r\n");
      out.write("    <!-- End of Header -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Start of Main -->\r\n");
      out.write("    <main class=\"main login-page\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"page-content\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"login-popup\">\r\n");
      out.write("                    <div class=\"tab tab-nav-boxed tab-nav-center tab-nav-underline\">\r\n");
      out.write("                        <ul class=\"nav nav-tabs text-uppercase\" role=\"tablist\">\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a href=\"#sign-in\" class=\"nav-link active\">Sign In</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                            <li class=\"nav-item\">\r\n");
      out.write("                                <a href=\"#sign-up\" class=\"nav-link\">Sign Up</a>\r\n");
      out.write("                            </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <div class=\"tab-content\">\r\n");
      out.write("                            <div class=\"tab-pane active\" id=\"sign-in\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label>Email address *</label>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" name=\"username\" id=\"login_email\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group mb-0\">\r\n");
      out.write("                                    <label>Password *</label>\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" name=\"password\" id=\"login_password\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <span style=\"color: red\" id=\"error\"></span>\r\n");
      out.write("                                <div class=\"form-checkbox d-flex align-items-center justify-content-between\">\r\n");
      out.write("                                    <input type=\"checkbox\" class=\"custom-checkbox\" id=\"remember1\" name=\"remember1\" required=\"\">\r\n");
      out.write("                                    <label for=\"remember1\">Remember me</label>\r\n");
      out.write("                                    <a href=\"#\">Last your password?</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"#\" id=\"logIn\" class=\"btn btn-primary\">Sign In</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"tab-pane\" id=\"sign-up\">\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label>Email</label>\r\n");
      out.write("                                    <input type=\"email\" class=\"form-control\" name=\"email\" id=\"useremail\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label>Name</label>\r\n");
      out.write("                                    <input type=\"name\" class=\"form-control\" name=\"name\" id=\"name\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group\">\r\n");
      out.write("                                    <label>Address</label>\r\n");
      out.write("                                    <input type=\"address\" class=\"form-control\" name=\"address\" id=\"address\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-group mb-5\">\r\n");
      out.write("                                    <label>Password</label>\r\n");
      out.write("                                    <input type=\"password\" class=\"form-control\" name=\"password\" id=\"pass\" required>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"form-checkbox user-checkbox mt-0\">\r\n");
      out.write("                                    <input type=\"checkbox\" class=\"custom-checkbox checkbox-round active\" id=\"check-customer\" name=\"check-customer\" required=\"\">\r\n");
      out.write("                                    <label for=\"check-customer\" class=\"check-customer mb-1\">I am a customer</label>\r\n");
      out.write("                                    <br>\r\n");
      out.write("                                    <input type=\"checkbox\" class=\"custom-checkbox checkbox-round\" id=\"check-seller\" name=\"check-seller\" required=\"\">\r\n");
      out.write("                                    <label for=\"check-seller\" class=\"check-seller\">I am a vendor</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p>Your personal data will be used to support your experience\r\n");
      out.write("                                    throughout this website, to manage access to your account,\r\n");
      out.write("                                    and for other purposes described in our <a href=\"#\" class=\"text-primary\">privacy policy</a>.</p>\r\n");
      out.write("                                <a href=\"#\" class=\"d-block mb-5 text-primary\">Signup as a vendor?</a>\r\n");
      out.write("                                <div class=\"form-checkbox d-flex align-items-center justify-content-between mb-5\">\r\n");
      out.write("                                    <input type=\"checkbox\" class=\"custom-checkbox\" id=\"remember\" name=\"remember\" required=\"\">\r\n");
      out.write("                                    <label for=\"remember\" class=\"font-size-md\">I agree to the <a  href=\"#\" class=\"text-primary font-size-md\">privacy policy</a></label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <a href=\"#\" id=\"signUp\" class=\"btn btn-primary\">Sign Up</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <p class=\"text-center\">Sign in with social account</p>\r\n");
      out.write("                        <div class=\"social-icons social-icon-border-color d-flex justify-content-center\">\r\n");
      out.write("                            <a href=\"#\" class=\"social-icon social-facebook w-icon-facebook\"></a>\r\n");
      out.write("                            <a href=\"#\" class=\"social-icon social-twitter w-icon-twitter\"></a>\r\n");
      out.write("                            <a href=\"#\" class=\"social-icon social-google fab fa-google\"></a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </main>\r\n");
      out.write("    <!-- End of Main -->\r\n");
      out.write("\r\n");
      out.write("    <!-- Start of Footer -->\r\n");
      out.write("\r\n");
      out.write("    <!-- End of Footer -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- End of Page Wrapper -->\r\n");
      out.write("\r\n");
      out.write("<!-- End of Mobile Menu -->\r\n");
      out.write("\r\n");
      out.write("<!-- Plugin JS File -->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    document.getElementById('signUp').addEventListener('click',function (){\r\n");
      out.write("        let email = document.getElementById('useremail').value;\r\n");
      out.write("        let name = document.getElementById('name').value;\r\n");
      out.write("        let address = document.getElementById('address').value;\r\n");
      out.write("        let password = document.getElementById('pass').value;\r\n");
      out.write("\r\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("signup',{\r\n");
      out.write("            method:'post',\r\n");
      out.write("            headers:{'Content-Type':'application/json'},\r\n");
      out.write("            body:JSON.stringify({\r\n");
      out.write("                email:email,\r\n");
      out.write("                name:name,\r\n");
      out.write("                address:address,\r\n");
      out.write("                password:password,\r\n");
      out.write("            })\r\n");
      out.write("        })\r\n");
      out.write("            .then(response=>response.text())\r\n");
      out.write("            .then(text=>{\r\n");
      out.write("                if (text == \"success\"){\r\n");
      out.write("                    window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/luminary';\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    document.getElementById('logIn').addEventListener('click',function (){\r\n");
      out.write("        let login_email = document.getElementById('login_email').value;\r\n");
      out.write("        let login_password = document.getElementById('login_password').value;\r\n");
      out.write("\r\n");
      out.write("        fetch('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("login',{\r\n");
      out.write("            method:'post',\r\n");
      out.write("            headers:{'Content-Type':'application/json'},\r\n");
      out.write("            body:JSON.stringify({\r\n");
      out.write("                email:login_email,\r\n");
      out.write("                password:login_password\r\n");
      out.write("            })\r\n");
      out.write("        })\r\n");
      out.write("            .then(response=>response.text())\r\n");
      out.write("            .then(text=>{\r\n");
      out.write("                if (text == \"success\"){\r\n");
      out.write("                    window.location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/luminary';\r\n");
      out.write("                }else{\r\n");
      out.write("                    document.getElementById(\"error\").textContent = \"Invalid Email or Password\";\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("    })\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"assets/vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"assets/vendor/magnific-popup/jquery.magnific-popup.min.js\"></script>\r\n");
      out.write("<script src=\"assets/js/main.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
